-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE EMP
(
  EMPNO     SMALLINT,
  ENAME     VARCHAR(10),
  JOB       VARCHAR(9),
  MGR       SMALLINT,
  HIREDATE  TIMESTAMP(0),
  SAL       DECIMAL(7,2),
  COMM      DECIMAL(7,2),
  DEPTNO    SMALLINT,
  ACCOUNT   TEXT
)
;

COMMENT ON COLUMN EMP.EMPNO IS 'Employee number';

COMMENT ON COLUMN EMP.ENAME IS 'Name';

COMMENT ON COLUMN EMP.JOB IS 'Job';

COMMENT ON COLUMN EMP.MGR IS 'Direct superior';

COMMENT ON COLUMN EMP.HIREDATE IS 'Date of joining the company';

COMMENT ON COLUMN EMP.SAL IS 'Salary';

COMMENT ON COLUMN EMP.COMM IS 'Bonus';

COMMENT ON COLUMN EMP.DEPTNO IS 'Department number';


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE DEPT
(
  DEPTNO  SMALLINT,
  DNAME   VARCHAR(14),
  LOC     VARCHAR(13)
)
;


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE EMP_FILE
(
  EMPNO      VARCHAR(4),
  FILE_NAME  VARCHAR(50),
  FILE_DATA  BYTEA
)
;


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX EMP_FILE_PK ON EMP_FILE
(EMPNO)
;


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX PK_DEPT ON DEPT
(DEPTNO)
;


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX PK_EMP ON EMP
(EMPNO)
;

ALTER TABLE EMP ADD PRIMARY KEY (EMPNO);

ALTER TABLE DEPT ADD PRIMARY KEY (DEPTNO);

ALTER TABLE EMP_FILE ADD PRIMARY KEY (EMPNO);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into DEPT
   (DEPTNO, DNAME, LOC)
 Values
   (10, 'ACCOUNTING', 'NEW YORK');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into DEPT
   (DEPTNO, DNAME, LOC)
 Values
   (20, 'RESEARCH', 'DALLAS');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into DEPT
   (DEPTNO, DNAME, LOC)
 Values
   (30, 'SALES', 'CHICAGO');
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into DEPT
   (DEPTNO, DNAME, LOC)
 Values
   (40, 'OPERATIONS', 'BOSTON');



-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (1111, 'Hong Gildong', 'Manager', 22, TO_DATE('01/02/2012 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 5555, 10);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7369, 'SMITH', 'CLERK', 7902, TO_DATE('12/17/1980 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 4157.28, 30);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('02/20/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1607, 30);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
 Values
   (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('02/22/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1250, 500, 30);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, DEPTNO)
 Values
   (7566, 'JONES', 'MANAGER', 7839, TO_DATE('04/02/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 20);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
 Values
   (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('09/28/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1250, 1400, 10);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('05/01/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2850, 30);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('06/09/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2450, 10);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7788, 'SCOTT', 'ANALYST', 7566, TO_DATE('04/19/1987 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3000, 20);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, HIREDATE, SAL, DEPTNO)
 Values
   (7839, 'KING', 'PRESIDENT', TO_DATE('11/17/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 5000, 10);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
 Values
   (7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('09/08/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1500, 0, 30);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7876, 'ADAMS', 'CLERK', 7788, TO_DATE('05/23/1987 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1100, 20);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7900, 'JAMES', 'CLERK', 7698, TO_DATE('12/03/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 950, 30);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7902, 'FORD', 'ANALYST', 7566, TO_DATE('12/03/1981 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 3000, 20);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
Insert into EMP
   (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
 Values
   (7934, 'MILLER', 'CLERK', 7782, TO_DATE('01/23/1982 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1300, 10);

commit;

