var WebSquareLang = {
    //core.js
    //Actions.js
    E_Actions_fileuploadPopupName: "File Uploading : %1",
    //date.js
    E_date_ShouldBeyyMMddFormat: "Input in yyyyMMdd format. Your input is %1.",
    E_date_month_ShouldBeyyMMFormat: "Input in yyyyMM format. Your input is %1.",
    E_date_hour_ShouldBeyyMMddHHFormat: "Input in yyyyMMddHH format. Your input is %1.",
    E_date_minute_ShouldBeyyMMddHHmmFormat: "Input in yyyyMMddHHmm format. Your input is %1.",
    E_date_minute_ShouldBeHHmmssFormat: "Input in HHmmss format. Your input is %1.",
    E_date_minute_ShouldBeHHmmFormat: "Input in HHmm format. Your input is %1.",
    E_date_ShouldBeNumberFormat: "Input numeric values. Your input is %1.",
    E_date_YearRange: "Input the year between %1 and %2. Your input is %3.",
    E_date_MonthRange: "Input the month between %1 and %2. Your input is %3.",
    E_date_DayRange: "Input the day between %1 and %2. Your input is %3.",
    E_date_HourRange: "Input the hour between %1 and %2. Your input is %3.",
    E_date_MinuteRange: "Input the minute between %1 and %2. Your input is %3.",
    E_date_SecondRange: "Input the second between %1 and %2. Your input is %3.",
    //exception.js
    E_exception_ErrorOccursSeeLog: "An error occurred. See the following messages.\n%1",
    E_exception_IERuntimeError: "Runtime Error\n    Line No.    : %1 \n    Character : %2 \n    Code : %3 \n    URL : %4 \n    Error : %5 \n    Original Text : %6 ",
    E_exception_FFRuntimeError: "Runtime Error\n    Line No.    : %1 \n    URL : %2 \n    Error : %3 \n    Original Text : %4 ",
    //form.js
    E_form_TimeKeyUpWrongHourFormat: "Invalid hour format.",
    E_form_TimeKeyUpWrongMinuteFormat: "Invalid minute format.",
    //initializer.js
    E_initializer_XMLLoadFailError: "Fail to read the WebSquare XML File. Please check the URL. [ %1 ]",
    E_initializer_XMLLoadFailError1: "Fail to process the WebSquare XML File. [ %1 ]",
    //logger.js
    E_logger_ContextmenuSeeLog: "View logs",
    E_logger_ContextmenuSeePerformanceLog: "View performance logs",
    E_logger_ContextmenuSeeAddress: "Address",
    E_logger_ContextmenuSeeQR: "View QR",
    E_logger_ContextmenuSeeSource: "View source",
    E_logger_ContextmenuSeeCollection: "View dataCollection",
    E_logger_ContextmenuSeeInstance: "View Instance",
    E_logger_ContextmenuSeeFiddle: "View fiddle",
    E_logger_ContextmenuSeeSubmission: "View submission",
    E_logger_ContextmenuStopDebugOnScreen: "Stop debugging on this screen",
    E_logger_ContextmenuStartDebugOnScreen: "Start debugging on this screen",
    E_logger_ContextmenuStopDebugOnSystem: "Stop debugging on the system",
    E_logger_ContextmenuStartDebugOnSystem: "Start debugging on the system",
    E_logger_ContextmenuStartEventDebug: "Start event debugging",
    E_logger_ContextmenuStopEventDebug: "Stop event debugging",
    E_logger_ContextmenuPrint: "Print",
    E_logger_ContextmenuRefresh: "Refresh",
    E_logger_ContextmenuPageReload: "Reset Page",
    E_logger_ContextmenuPageReloadWframe: "Reset wframe",
    E_logger_ContextmenuBrowserReload: "Reset Browser",
    E_logger_ContectmenuFileInfo: "File Info",
    E_logger_ContextmenuVersion: "Version",
    E_logger_EnterPassword: "Please enter the password.",
    E_logger_IncorrectPassword: "The password is incorrect.",
    E_logger_ObjectDisabled: "The object is disabled.",
    E_logger_UsedXSLInfo: "XSL : %1",
    E_logger_NoUsedXSLInfo: "There is no XSL File to draw this component.",
    E_logger_InnerBlindObject: "[This object cannot attach inner structure.]\n\n",
    E_logger_InitDueToOverline: "%1 [%2] Logs exceeded 500 lines. Initializing logs.",
    E_logger_ObjectInfo: "Object Information",
    E_logger_XSLInfo: "XSL Information",
    E_logger_changeClientName: "Please enter the name of the client for remote debugging.",
    //Model.js
    E_Model_NoChildNodeOfInstance: "The instance does not have a child node.",
    //ModelUtil.js
    E_ModelUtil_NoSubmissionObjectWithID: "The submission object [%1] does not exist.",
    E_ModelUtil_NoSubmissionObject: "The submission object does not exist.",
    //net.js
    E_net_PopupBlocked: "Pop-ups are blocked.",
    //Parser.js
    E_Parser_MoreThanOneHeadError: "WebSquare allows only one <head> tag in the XML file. \n But this file has '%1' <head> tags.",
    E_Parser_MoreThanOneBodyError: "WebSquare allows only one <body> tag in the XML file. \n But this file has '%1' <body> tags.",
    //WebSquareDocument.js
    E_WebSquareDocument_MoreThanOneBodyError: "WebSquare allows only one <body> tag in the XML file. \n But this file has '%1' <body> tags.",
    //xml.js
    E_xml_XMLUnsupportedBrowser: "The current browser does not support XML.",
    E_xml_ErrorOccurLoadingXMLWithURL: "An error occurred during XML loading.\n\nURL : %1",
    E_xml_ErrorOccurLoadingXML: "An error occurred during XML loading.\n",
    E_xml_ErrorOccurParsingXML: "An error occurred during XML parsing.\n",
    //core.js
    E_core_AjaxUnsupportedBrowser: "The current browser does not support Ajax.",
    E_core_NoPluginError: "Plugin[ %1 ] does not exist.",
    E_core_NoModuleError: "Module[ %1 ] does not exist.",
    //event.js
    E_event_AddEventError: "Error: an HTML object doesn't have ID or the current version does not support the action[ %1 ].",
    E_dc_duplicated_Msg: "id[%1] is duplicated, so the existing %2 has been deleted, and a new one has been created.",
    E_comp_duplicated_Msg: "id[%1] is duplicated. Check the source code.",
    //logMsg.html
    E_logMsg_LogInfo: "Log Information.",
    E_logMsg_LogAutoRenewal: "Auto updating...",
    E_logMsg_LogAutoRenewalStop: "Stopped auto updating.",
    //QR.html
    E_viewQR_title: "QR Information.",
    //viewSource.html
    E_viewSource_title: "Source Information.",
    //viewCollection.html
    E_viewCollection_title: "Collection Information.",
    //viewInstance.html
    E_viewInstance_title: "Instance Information.",
    //viewSubmission.html
    E_viewSubmission_title: "Submission Information.",
    //debugMsg.html
    E_debugMsg_DebugInfo: "Debug Information.",
    //processMsg.html
    E_processMsg_Processing: "Processing...",
    //errorMsg.html
    E_errorMsg_ErrorInfo: "Error Information.",
    //deprecated
    E_deprecated_sync: "Synchronous XMLHttpRequest on the main thread is deprecated of its detrimental effects to the end user's experience.[%1]",
    //validator
    V_error_minLength: "Enter minimum %1 digit(s).",
    V_error_maxLength: "Enter not more than %1 digit(s).",
    V_error_minByteLength: "Enter minimum %1 byte(s).",
    V_error_maxByteLength: "Enter not more than %1 byte(s).",
    V_error_validCondition: "The execution conditions of the validator are not satisfied.",
    V_error_no_valiator: "Validator does not exist or it is not an object.",
    V_error_mandatory: "Mandatory",
    V_error_allowChar: "String %1 is allowed.",
    V_error_ignoreChar: "String %1 is not allowed.",
    V_error_date: "Invalid date format",
    V_error_float: "Invalid float format",
    AllText: "all",
    //formatter
    F_dateFormat_daynames_abbr: "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    F_dateFormat_daynames_full: "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday",
    IC_Mask: "yyyy-MM-dd",
    IC_Delimiter: "-",
    IC_invalidCalendarSelect: "Invalid date format",
    GRID_noResultMsg: "There is no search result.",
    GRID_useFilterEmptyMsg: " Empty",
    GRID_useFilterNullMsg:"Null",
    SelectBox_all: "-all-",
    SelectBox_choose: "-choose-",
    //CheckCombobox
    CheckCombobox_all: "choose all",
    CheckCombobox_choose: "choose",
    CheckCombobox_allOption_label: "choose all",
    CheckCombobox_label: "label",
    // Calendar
    Calendar_select_year: "Select year",
    Calendar_select_month: "Select month",
    Calendar_select_hour: "Select hour",
    Calendar_valuetype_hour: "h",
    Calendar_select_minute: "Select minute",
    Calendar_valuetype_minute: "m",
    Calendar_select_second: "Select second",
    Calendar_valuetype_second: "s",
    Calendar_previous_year: "Previous Year",
    Calendar_previous_month: "Previous Month",
    Calendar_next_year: "Next Year",
    Calendar_next_month: "Next Month",
    Calendar_ok: "OK",
    Calendar_open: "Calendar",
    Calendar_close: "Close",
    Calendar_cancel: "Cancel",
    Calendar_reset: "Reset",
    Calendar_today: "Today",
    Calendar_name: "Calendar",
    Calendar_caption: "Calendar",
    Calendar_summary: "Calendar: Select the date.",
    Calendar_yearsuffix: "",
    Calendar_monthnames: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    Calendar_weekdaynames_0: "Sunday",
    Calendar_weekdaynames_1: "Monday",
    Calendar_weekdaynames_2: "Tuesday",
    Calendar_weekdaynames_3: "Wednesday",
    Calendar_weekdaynames_4: "Thursday",
    Calendar_weekdaynames_5: "Friday",
    Calendar_weekdaynames_6: "Saturday",
    Calendar_weekdaynames_short_0: "Sun",
    Calendar_weekdaynames_short_1: "Mon",
    Calendar_weekdaynames_short_2: "Tue",
    Calendar_weekdaynames_short_3: "Wed",
    Calendar_weekdaynames_short_4: "Thu",
    Calendar_weekdaynames_short_5: "Fri",
    Calendar_weekdaynames_short_6: "Sat",
    Calendar_tooltip: "%2-%3-%1",
    Calendar_select_title: "selected date",
    Calendar_start: "calendar start",
    Calendar_info1: "Since the calendarValueType option of %1 is 'yearMonthDate', the strings that can be used as arguments for the setDateFormat API are yyyy, MM, and dd.",
    Calendar_inof2: "Since the calendarValueType option of %1 is 'yearMonth', the strings that can be used as arguments for the setDateFormat API are yyyy, MM.",
    Calendar_info3: "Since the calendarValueType option of %1 is 'yearMonthDateHour', the strings that can be used as arguments for the setDateFormat API are yyyy, MM, dd, HH.",
    Calendar_info4: "Since the calendarValueType option of %1 is 'yearMonthDateTime', the strings that can be used as arguments for the setDateFormat API are yyyy, MM, dd, HH, mm.",
    //date
    Date_err_1900: "Year starts from 1900.",
    Date_err_12: "Month cannot be greater than 12.",
    Date_err_31: "Day cannot be greater than 31.",
    Date_err_29: "February has 29 days.",
    Date_err_28: "February has 28 days.",
    Date_err_30: "has 30 days.",
    //multiupload
    MultiUpload_all: "All files",
    MultiUpload_image: "Pictures",
    MultiUpload_add: "add",
    MultiUpload_delete: "delete",
    MultiUpload_cancel: "cancel",
    MultiUpload_send: "send",
    MultiUpload_addFile: "add file",
    MultiUpload_file: "file",
    MultiUpload_size: "size",
    MultiUpload_status: "status",
    MultiUpload_complete: "Complete",
    MultiUpload_err_fileExist: "File already exists (%1)",
    MultiUpload_err_maxCountExceed: "The upload count is limited to %1.",
    MultiUpload_err_fileSizeExceed: "Upload file size is limited to %1 ",
    MultiUpload_err_HTTPExcpetion: "HTTP error occured. (status : %1)",
    // Pagelist
    Pagelist_first_page: "First Page",
    Pagelist_previous_page: "Previous Page",
    Pagelist_previous: "Previous",
    Pagelist_next_page: "Next Page",
    Pagelist_next: "Next",
    Pagelist_nextList_page: "Next list of %1 pages",
    Pagelist_previousList_page: "Previous list of %1 pages",
    Pagelist_last_page: "Last Page",
    Pagelist_selected: "%1 selected",
    Pagelist_previous_ellipsisText: "Previous items omitted",
    Pagelist_next_ellipsisText: "Next items omitted",
    // slider
    Slider_warning1: "Enter a value between %1 and %2.",
    Slider_warning2: "Increase the value between %1 and %2 by %3.",
    Slider_range: "Input Type Range",
    // Window
    Window_minimize: "Minimize",
    Window_restore: "Restore",
    Window_close: "Close",
    Window_cancel: "Cancel",
    Window_popup: "Popup",
    Window_statusMsg: "Loading...",
    Window_popup_start: "popup start",
    // WindowContainer
    WindowContainer_controlIcon_maximize: "Maximize/Restore",
    WindowContainer_controlIcon_vertical: "Tile Vertically",
    WindowContainer_controlIcon_horizontal: "Tile Horizontally",
    WindowContainer_controlIcon_cascade: "Cascade",
    WindowContainer_controlIcon_sequential: "Grid",
    WindowContainer_controlIcon_closeAll: "Close All",
    WindowContainer_controlIcon_closeOthers: "Close All except Active window",
    WindowContainer_controlIcon_windowList: "Open the list of windows",
    WindowContainer_maxNum_warning: "Maximum %1 screens can be displayed.",
    WindowContainer_confirm_warning: "#title screen exists. Select 'OK' to use the existing window, or 'Cancel' to use a new window.",
    WindowContainer_maximize: "Maximize",
    WindowContainer_restore: "Restore",
    WindowContainer_next: "Previous window",
    WindowContainer_previous: "Next window",
    WindowContainer_empty_status: "Empty state",
    WindowContainer_default_view_status: "Current default view",
    WindowContainer_horizontal_align: "Horizontal alignment",
    WindowContainer_horizontal_align_status: "Current window in horizontal layout view",
    WindowContainer_vertical_align: "Vertical alignment",
    WindowContainer_vertical_align_status: "Current window in vertical layout view",
    WindowContainer_cascade_align: "Cascade alignment",
    WindowContainer_cascade_align_status: "Current window in cascading layout view",
    WindowContainer_tiled_align: "Tiled alignment",
    WindowContainer_tiled_align_status: "Current window in Tiled layout view",
    WindowContainer_windowList: "Window list",
    WindowContainer_fix_dialog: "Fix dialog box",
    WindowContainer_fix_dialog_set: "Fix dialog box selected",
    WindowContainer_fix_dialog_unset: "Fix dialog box deselected",
    WindowContainer_close_dialog: "Close dialog",
    WindowContainer_custom: "Custom",
    WindowContainer_dualMonitors: "Dual Monitors",
    WindowContainer_multiView: "Multi View",
    WindowContainer_share: "Share",
    WindowContainer_minimizeSize_status: "minimized size",
    WindowContainer_defaultSize_status: "default size",
    WindowContainer_maximizeSize_status: "maximize size",
    // WidgetContainer
    WidgetContainer_setCols_warning: "Invalid cols.",
    WidgetContainer_maximize: "maximize button",
    WidgetContainer_minimize: "minimize button",
    WidgetContainer_minimizeSize_status: "minimized size",
    WidgetContainer_defaultSize_status: "default size",
    WidgetContainer_maximizeSize_status: "maximize size",
    WidgetContainer_fix: "fix",
    WidgetContainer_fix_set: "selected",
    WidgetContainer_fix_unset: "cancel",
    WidgetContainer_close: "close",
    // DatePicker
    DatePicker_yearSuffix: "$blank",
    DatePicker_monthNames: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    DatePicker_dateSuffix: "$blank",
    DatePicker_ampm: "am,pm",
    DatePicker_select_year : "SelectYear",
    DatePicker_select_month : "SelectMonth",
    DatePicker_select_date : "SelectDate",
    DatePicker_select_ampm : "SelectAmPm",
    DatePicker_select_hour : "SelectHour",
    DatePicker_select_minutes : "SelectMinutes",
    // chart
    Chart_context_chartType: "Chart Type",
    Chart_context_chartOption: "Chart Option",
    Chart_context_chartStyle: "Chart Style",
    Chart_context_seriseOption: "Series Option",
    Chart_main_axis: "Main Axis",
    Chart_auxiliary_axis: "Auxiliary Axis",
    Chart_warning_msg1: "Incorrect data",
    Chart_warning_load_default_version: "load as the default version %1",
    Chart_warning_incorrect_chart_version: "Incorrect Chart version",
    Chart_warning_no_resource: "No resource corresponding to the chart version",
    // tabControl
    TabControl_maxNum_warning: "Maximum %1 tabs are allowed",
    TabControl_close: "Close",
    TabControl_close_all: "Close All",
    TabControl_right_corner: "Right-corner Image",
    TabControl_left_corner: "Left-corner Image",
    TabControl_warning1: "[#title] already exists. Click OK to use the existing tab, or click Cancel to create a new tab.",
    TabControl_previous_tab: "previous tab",
    TabControl_next_tab: "next tab",
    TabControl_tab_list: "list of tab",
    TabControl_selected: "%1 selected",
    //autoComplete
    AutoComplete_addItem_invalid: "An item value is already in %2 at %1. Item value should be unique.",
    AutoComplete_all: "-all-",
    AutoComplete_choose: "-choose-",
    AutoComplete_inputFormat: "Input Format",
    AutoComplete_label: "AutoComplete",
    // grid
    Grid_sort_none: "Unsort",
    Grid_sort_asc: "Ascending Sort",
    Grid_sort_desc: "Descending Sort",
    Grid_sort_asc_info: "Sorted ascending by %1 cell",
    Grid_sort_desc_info: "Sorted descending by %1 cell",
    Grid_filter_title: "Custom Filter",
    Grid_filter_search: "Search",
    Grid_filter_search_label: "Search criteria",
    Grid_filter_condition1: "Starting character",
    Grid_filter_condition2: "Starting character to be excluded",
    Grid_filter_condition3: "Ending characters",
    Grid_filter_condition4: "Ending character to be excluded",
    Grid_filter_condition5: "Include",
    Grid_filter_condition6: "Exclude",
    Grid_filter_condition7: "= (Metacharacter)",
    Grid_filter_info_Label1: "? matches any single character",
    Grid_filter_info_Label2: "* matches matches zero or more characters.",
    Grid_filter_confirm: "OK",
    Grid_filter_cancel: "Cancel",
    Grid_filter_reset: "Reset",
    Grid_filter_button: "Filter button",
    Grid_Customized_Filter: "Customized Filter",
    Grid_column_hide: "Hide",
    Grid_column_showAll: "Show All Columns",
    Grid_column_fix: "Fix",
    Grid_column_unfix: "Unfix All Columns",
    Grid_column_adjustWidth: "Adjust Width",
    Grid_column_adjustAuto: "Adjust All Column Widths",
    Grid_column_adjustAuto_none: "UnAdjust All Column Widths",
    Grid_fold_all: "Fold All",
    Grid_unfold_all: "Unfold All",
    Grid_ungroup_all: "Ungroup All",
    Grid_ungroup: "Ungroup",
    Grid_group: "Group",
    Grid_noResultMessage: "No search result.",
    Grid_scrollMsg: "Updating...",
    Grid_all: "-all-",
    Grid_checked_all: "choose all",
    Grid_incorrect_inputType: "inputType is incorrect.",
    Grid_warning1: "The selected column is not a checkbox.",
    Grid_warning2: "Invalid data format encountered. Expected 'true' or 'false', please re-enter.",
    Grid_warning3: "inputType is neither a checkbox nor a radio button.",
    Grid_warning4: "[%1] Changing setting %2 is not currently supported",
    Grid_warning5: " %1 Adaptive mode not supported for this grid.",
    Grid_warning6: "[%1] The groupby is enabled and the lazyDrawHiddenColumn is disabled.",
    Grid_warning7: "%1 : rowSpan is enabled the lazyDrawHiddenColumn is disabled.",
    Grid_warning8: "The cell count has exceeded the limit.\n The current limit is : %1.",
    Grid_warning9: "The data size has exceeded the limit.\n The current limit is : %1 byte",
    Grid_warning10: "The row count has exceeded the limit.\n The current limit is : %1",
    Grid_caption: " displayed in the table",
    Grid_caption2: " is ",
    Grid_caption_shortcut: "Press CTRL and END together to move focus to the last cell of the table.",
    Grid_footer_caption: "total is displayed in the table",
    Grid_title: " checked",
    Grid_title_not_choose: " unchecked",
    Grid_title_partial: " partial checked",
    Grid_button: " button",
    Grid_select: " select",
    Grid_calendar: " calendar",
    Grid_secret: " secret",
    Grid_text: "text",
    Grid_link: " link",
    Grid_autoComplete: " autoComplete",
    Grid_more_Button: "more",
    Grid_rowStatus_initialValue: "initial value", // R
    Grid_rowStatus_update: "updated", // U
    Grid_rowStatus_insert: "inserted", // C
    Grid_rowStatus_delete: "deleted", // D
    Grid_rowStatus_D_After_C: "deleted after insertion", // V
    Grid_cases: "cases",
    Grid_dom_start: "Grid start",
    Grid_dom_end: "Grid end",
    Grid_row: "row",
    Grid_column: "column",
    Grid_groupby_count: "items",
    //fwGanttChart
    fwGanttChart_ampm: "AM,PM",
    fwGanttChart_yearSuffix: "$blank",
    fwGanttChart_monthSuffix: "$blank",
    fwGanttChart_dateSuffix: "$blank",
    fwGanttChart_timeGap3Label: "midnight,am 3,am 6,am 9,noon,pm 3,pm 6,pm 9",
    fwGanttChart_timeGap6Label: "midnight,am 6,noon,pm 6",
    fwGanttChart_quarterNames: "Q1,Q2,Q3,Q4",
    fwGanttChart_monthNames: "Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec",
    //mapchart
    Map_name_39: "Jeju",
    Map_name_38: "Gyeongnam",
    Map_name_36: "Jeonnam",
    Map_name_35: "Jeonbuk",
    Map_name_34: "Chungnam",
    Map_name_33: "Chungbuk",
    Map_name_32: "Gangwon",
    Map_name_31: "Gyeonggi",
    Map_name_29: "Sejong",
    Map_name_26: "Ulsan",
    Map_name_25: "Daejeon",
    Map_name_24: "Gwangju",
    Map_name_22: "Daegu",
    Map_name_21: "Busan",
    Map_name_11: "Seoul",
    Map_name_37: "Gyeongbuk",
    Map_name_23: "Incheon",
    // upload
    Upload_ignore_spaces: "Ignore blank spaces",
    Upload_include_spaces: "Include blank spaces",
    Upload_advanced: "Advanced",
    Upload_hidden_values: "Hidden values",
    Upload_include: "Include",
    Upload_not_include: "Not include",
    Upload_fill_hidden: "Fill Hidden",
    Upload_sheet_no: "Sheet No",
    Upload_starting_row: "Start row",
    Upload_starting_col: "Start col",
    Upload_header: "Header",
    Upload_footer: "Footer",
    Upload_file: "Upload File",
    Upload_file_title: "FILE UPLOAD",
    Upload_file_header: "File Upload",
    Upload_file_choose: "Choose File",
    Upload_file_span: "No file chosen",
    Upload_fill: "fill",
    Upload_ignore: "ignore",
    Upload_pwd: "Password",
    Upload_msg1: "Temporary Frame for File Uploading",
    Upload_msg2: "File size exceeding the limit.",
    Upload_msg3: "Normal processing failed.",
    Upload_msg4: "Check the file extension.",
    Upload_msg5: "Failed to reflect on the grid.",
    Upload_msg6: "Collecting data..",
    Upload_msg7: "Data conversion completed.",
    Upload_msg8: "The password is incorrect.",
    Upload_msg9: "Check the file extension.",
    Upload_msg10: "An error occurred during DRM.",
    Upload_msg11: "Row count exceeding the limit.",
    Upload_msg12: "Invalid file format.",
    Upload_msg13: "Invalid cell format",
    Upload_msg14: "Cell count exceeding the limit.",
    Upload_msg15: "This file is encryped.",
    Upload_msg16: "Not support Excel 5.0/7.0",
    Upload_msg17: "Does not sheet number.",
    Upload_msg18: "It is a write-only file or an unreadable file.",
    Upload_warning1: "Inaccessible for security purposes.",
    //datalist
    DataList_msg1: "An unexpected error occurred during processing.",
    DataList_msg2: "The user-defined provider class could not be found.",
    DataList_msg3: "An error occurred while generating data linked to the user-defined provider.",
    DataList_msg4: "Processing was terminated because the status was set to false.",
    DataList_msg5: "Processing was stopped because the maximum number of rows that can be received was exceeded.",
    //itemTable
    itemTable_confirm: "confirm",
    itemTable_cancel: "cancel",
    //pivot
    Pivot_canNotMoveToHiddenList: "This Column can not move to Hidden List.",
    Pivot_sum: " sum",
    Pivot_average: " average",
    Pivot_count: " count",
    Pivot_min: " Minimum value",
    Pivot_max: " Maximum value",
    Pivot_renderError: "An error occurred rendering the PivotTable results.",
    Pivot_computeError: "An error occurred computing the PivotTable results.",
    Pivot_uiRenderError: "An error occurred rendering the PivotTable UI.",
    Pivot_dragError: "Grand totals cannot be dragged into the Value area.",
    Pivot_selectAll: "Select All",
    Pivot_selectNone: "Select None",
    Pivot_tooMany: "(too many to list)",
    Pivot_filterResults: "Filter results",
    Pivot_totals: "Totals",
    Pivot_vs: "vs",
    Pivot_by: "by",
    Pivot_apply: "apply",
    Pivot_cancel: "cancel",
    //slideHide
    SlideHide_btnHide: "hide",
    SlideHide_btnShow: "show",
    SlideHide_btnToggle: "show hide button",
    //switch
    Switch_btnPrev: "previous",
    Switch_btnNext: "next",
    Switch_pagination_ariaLabel: "pagination for %2 of %1",
    Switch_case_ariaRoledesc: "slide",
    Switch_case_ariaLabel: "%2 of %1",
    Switch_selected_pagination: "selected pagination",
    //searchbox
    Searchbox_ariaLabel: "search form",
    Searchbox_resetButton_ariaLabel: "clear input field",
    //treeview
    Treeview_iconNaviAriaLabel: "expand contract button",
    Treeview_warning1: "If you are processing the treeview dynamically, it is recommended to set dynamicAppend='true'",
    Treeview_warning2: "The spanAll API is not supported in treeview's accordion mode.",
    //multiselect
    multiselect_ariaLabel: "multiSelect area",
    multiselect_item_selected_ariaLabel: "%1 , selected",
    multiselect_item_deselected_ariaLabel: "%1 , deselected",
    //editor
    Editor_currentChar: "Characters",
    Editor_maxChar_warning: "Cannot exceed %1 characters.",
    Editor_warning_load_default_version: "load as the default version %1",
    Editor_warning_incorrect_editor_version: "Incorrect editor version",
    Editor_warning_no_resource: "No resource corresponding to the editor version",
    Editor_ariaLabel: "Editor, Press ALT 0 for help",
    //scheduleCalendar
    scheduleCalendar_schedule: "schedule",
    //performance
    Performance_step1: "Time elapsed from initiating a browser URL call until the 'BootLoader' finishes loading. 'BootLoader' is essential for the initial startup of the WebSquare engine.",
    Performance_step2: "Time elapsed from bootloader execution completion to the full loading of the WebSquare engine.",
    Performance_step3: "Time elapsed from engine loading completion to the complete loading of WebSquare Page File, Common JS, and CSS files.",
    Performance_step4: "Time elapsed from resource loading completion(WebSquare Page File, Common JS, and CSS files) to the creation of WebSquare component objects.",
    Performance_step5: "Time elapsed from component creation completion to the complete rendering of WebSquare components.",
    Performance_step6: "Time elapsed from rendering completion to the completion of component preprocessing",
    Performance_step7: "Time elapsed from preprocessing completion to the completion of component initialization.",
    Performance_step8: "Time elapsed from initialization completion to the execution of the initScript. Note: Asynchronous processing within initScript is excluded.",
    Performance_step9: "Time elapsed from initScript execution to the execution of the onpageload event. Note: Asynchronous processing within onpageload is excluded.",
    Performance_step10: "Time elapsed from onpageload execution to the execution of the postScript. Note: Asynchronous processing within postScript is excluded. WebSquare initialization completes at this stage, excluding any asynchronous processing.",
    Performance_event: "This metric measures the time taken for an event handler to execute from the start of the event until its completion. Asynchronous parts within the handler are excluded. Refer to the type attribute value for details regarding specific event types.",
    Performance_submission_start: "Time elapsed from the initiation of submission until the customHandler function call finishes. Note: Asynchronous processing within customHandler is excluded.",
    Performance_submission_end_replaceAll: "Time elapsed from the start of submission until submission processing completes in replace='all' mode. This involves creating a <form> element and processing the submission through the form.submit() method.",
    Performance_submission_step1: "Time elapsed from the start of submission until immediately before sending the URL request over the network.",
    Performance_submission_end_error_script: "Time elapsed from the start of submission until submission halts due to an error during processing.",
    Performance_submission_step2: "Time elapsed from sending the submission URL network request until the network response arrives, marking the beginning of the commonResponseHandler callback function.",
    Performance_submission_end_error_network: "Time elapsed from sending the submission URL request until submission forcefully terminates due to network response failure. This metric includes the network status code %1.",
    Performance_submission_step3: "Time elapsed from initiating the commonResponseHandler callback function to the completion of processing the submission's ref and target properties.",
    Performance_submission_end_ok: "The time elapsed from the completion of processing the submission's ref and target until the completion of the submission user event onsubmitdone. Submission processing is completed.",
    Performance_wframe_step1: "Time elapsed from wframe creation until completion of WebSquare Page File loading and DOM rendering (toHTML).",
    Performance_wframe_step2: "Time taken to execute wframe's 'initScript', 'onpageload', and 'postScript' events. Marks completion of wframe processing. Total elapsed time is the sum of step1 and end.",
    //accessibility
    Accssibility_btn_aria_label_windowContainer: "close window",
    //dragghost
    Drag_no_data: "no data"
};