var WebSquareLang = {

    //Actions.js
    E_Actions_fileuploadPopupName: "ファイルアップロード : %1",
    //date.js
    E_date_ShouldBeyyMMddFormat: "入力値はyyyyMMdd形式である必要があります。入力値：%1",
    E_date_month_ShouldBeyyMMFormat: "入力値はyyyyMM形式である必要があります。入力値：%1",
    E_date_hour_ShouldBeyyMMddHHFormat: "入力値はyyyyMMddHH形式である必要があります。入力値：%1",
    E_date_minute_ShouldBeyyMMddmmFormat: "入力値はyyyyMMddHHmm形式である必要があります。入力値：%1",
    E_date_minute_ShouldBeHHmmssFormat: "入力値はHHmmss形式である必要があります。入力値：%1",
    E_date_minute_ShouldBeHHmmFormat: "入力値はHHmm形式である必要があります。入力値：%1",
    E_date_ShouldBeNumberFormat: "入力値は数値形式である必要があります。入力値：%1",
    E_date_YearRange: "年度は%1から%2の間の値でなければなりません。入力値：%3",
    E_date_MonthRange: "月は%1から%2の間の値でなければなりません。入力値：%3",
    E_date_DayRange: "日は%1から%2の間の値でなければなりません。入力値：%3",
    E_date_HourRange: "時間は%1から%2の間の値でなければなりません。入力値：%3",
    E_date_MinuteRange: "分は%1から%2の間の値でなければなりません。入力値：%3",
    E_date_SecondRange: "秒は%1から%2の間の値でなければなりません。入力値：%3",
    //exception.js
    E_exception_ErrorOccursSeeLog: "作業中にエラーが発生しました。\n%1",
    E_exception_IERuntimeError: "Runtime Error\n    行 No.    : %1 \n    文字 : %2\n    コード : %3\n    URL : %4\n    エラー : %5\n    原本 : %6",
    E_exception_FFRuntimeError: "ランタイムエラー\n    行番号    : %1 \n    URL : %2 \n    エラー : %3 \n    原因 : %4 ",
    //form.js
    E_form_TimeKeyUpWrongHourFormat: "時間の入力が正しくありません。",
    E_form_TimeKeyUpWrongMinuteFormat: "分の入力が正しくありません。",
    //initializer.js
    E_initializer_XMLLoadFailError: "W2Xファイルの読み込みに失敗しました。パスを確認してください。URL [ %1 ]",
    E_initializer_XMLLoadFailError1: "読み込んだW2Xファイルの処理に失敗しました。URL [ %1 ]",   
    //logger.js
    E_logger_ContextmenuSeeLog: "ログを表示",
    E_logger_ContextmenuSeePerformanceLog: "パフォーマンスログを表示",
    E_logger_ContextmenuSeeAddress: "住所",
    E_logger_ContextmenuSeeQR: "QRコードを表示",
    E_logger_ContextmenuSeeSource: "ソースを表示",
    E_logger_ContextmenuSeeCollection: "dataCollectionを表示",
    E_logger_ContextmenuSeeInstance: "インスタンスを表示",
    E_logger_ContextmenuSeeFiddle: "Fiddleを表示",
    E_logger_ContextmenuSeeSubmission: "submission を表示",
    E_logger_ContextmenuStopDebugOnScreen: "現在の画面のデバッグを中断",
    E_logger_ContextmenuStartDebugOnScreen: "現在の画面でデバッグを実行",
    E_logger_ContextmenuStopDebugOnSystem: "全体システムデバッグ中断",
    E_logger_ContextmenuStartDebugOnSystem: "全体システムデバッグ実行",
    E_logger_ContextmenuStartEventDebug: "現在の画面イベント出力実行",
    E_logger_ContextmenuStopEventDebug: "現在の画面イベント出力を停止",
    E_logger_ContextmenuPrint: "印刷",
    E_logger_ContextmenuRefresh: "更新",
    E_logger_ContextmenuPageReload: "ページの初期化",
    E_logger_ContextmenuPageReloadWframe: "wframeの初期化",
    E_logger_ContextmenuBrowserReload: "ブラウザの初期化",
    E_logger_ContectmenuFileInfo: "ファイル情報",
    E_logger_ContextmenuVersion: "バージョン情報",
    E_logger_EnterPassword: "パスワードを入力してください。",
    E_logger_IncorrectPassword: "パスワードが一致しません。",
    E_logger_ObjectDisabled: "オブジェクトが無効になっています。",
    E_logger_UsedXSLInfo: "使用したXSL : %1",
    E_logger_NoUsedXSLInfo: "オブジェクトの描画に使用したXSLがありません。",
    E_logger_InnerBlindObject: "[内部構造を確認できないObjectです。]\n\n",
    E_logger_InitDueToOverline: "%1 [%2] ログが500行以上になったため、ログを初期化します。",
    E_logger_ObjectInfo: "Objectの情報",
    E_logger_XSLInfo: "XSL 情報",
    E_logger_changeClientName: "リモートデバッグに使用するClient Nameを入力してください。",
    //Model.js
    E_Model_NoChildNodeOfInstance: "該当instanceの子ノードが存在しません。",
    //ModelUtil.js
    E_ModelUtil_NoSubmissionObjectWithID: "submission オブジェクト[ %1 ]が存在しません。",
    E_ModelUtil_NoSubmissionObject: "submissionオブジェクトが存在しません。",
    //net.js
    E_net_PopupBlocked: "ポップアップが無効になりました。",
    //Parser.js
    E_Parser_MoreThanOneHeadError: "WebSquareのHeadは1つのみ許可されます。現在のXMLにはHeadが'%1'個あります。",
    E_Parser_MoreThanOneBodyError: "WebSquareのBodyは1つのみ許可されます。現在のXMLにはBodyが'%1'個あります。",
    //WebSquareDocument.js
    E_WebSquareDocument_MoreThanOneBodyError: "ウェブスクエアのBodyは1つのみ許可されます。現在のXMLにはBodyが'%1'個あります。",
    //xml.js
    E_xml_XMLUnsupportedBrowser: "XMLをサポートしていないブラウザーです。",
    E_xml_ErrorOccurLoadingXMLWithURL: "XMLをロードする際にエラーが発生しました。\n\nURL : %1",
    E_xml_ErrorOccurLoadingXML: "XMLをロードする際にエラーが発生しました。\n",
    E_xml_ErrorOccurParsingXML: "XMLをパージング中にエラーが発生しました。\n",
    //core.js
    E_core_AjaxUnsupportedBrowser: "Ajaxをサポートしていないブラウザーです。",
    E_core_NoPluginError: "プラグイン[ %1 ]が存在しません。",
    E_core_NoModuleError: "モジュール[ %1 ]が存在しません。",
    //event.js
    E_event_AddEventError: "IDのないHTMLオブジェクトが存在するか、現在のバージョンではサポートされていないAction[ %1 ]が使用されています。",
    E_dc_duplicated_Msg: "id[%1]が重複しています。既存の%2を削除して新しく生成します。",
    E_comp_duplicated_Msg: "id[%1] が重複使用されています。ソースコードを確認してください。",
    //logMsg.html
    E_logMsg_LogInfo: "ログ情報です。",
    E_logMsg_LogAutoRenewal: "自動更新中",
    E_logMsg_LogAutoRenewalStop: "自動更新停止",
    //QR.html
    E_viewQR_title: "QR Information.",
    //viewSource.html
    E_viewSource_title: "Source Information.",
    //viewColleciton.html
    E_viewCollection_title: "Collection Information.",
    //viewInstance.html
    E_viewInstance_title: "Instance Information.",
    //viewSubmission.html
    E_viewSubmission_title: "Submission Information.",
    //debugMsg.html
    E_debugMsg_DebugInfo: "デバッグ情報です。",
    //processMsg.html
    E_processMsg_Processing: "処理中です。",
    //errorMsg.html
    E_errorMsg_ErrorInfo: "エラー情報です。",
    //deprecated
    E_deprecated_sync: "同期（synchronous）通信は、パフォーマンスの問題により使用が推奨されません。非同期（asynchronous）通信の使用を推奨します。[%1]",
    //validator
    V_error_minLength: "最小%1桁以上入力する必要があります。",
    V_error_maxLength: "最大%1桁以上入力できません。",
    V_error_maxFloatLength: "最大整数%1桁、小数%2桁以上入力できません。",
    V_error_minByteLength: "最小%1バイト以上入力する必要があります。",
    V_error_maxByteLength: "最大 %1 バイト以上入力できません。",
    V_error_validCondition: "Validatorの実行条件を満たしていません。",
    V_error_no_valiator: "Validatorが存在しないか、オブジェクトではありません。",
    V_error_mandatory: "必須入力項目です",
    V_error_allowChar: "許可された文字列は%1です",
    V_error_ignoreChar: "許可されていない文字列は%1です",
    V_error_date: "日付の形式が正しくありません。",
    V_error_float: "小数形式が正しくありません。",
    AllText: "全体",
    //formatter
    F_dateFormat_daynames_abbr: "月,火,水,木,金,土,日",
    F_dateFormat_daynames_full: "月曜日·火曜日·水曜日·木曜日·金曜日·土曜日·日曜日",
    IC_Mask: "yyyy-MM-dd",
    IC_Delimiter: "-",
    IC_invalidCalendarSelect: "日付形式が正しくありません。",
    GRID_noResultMsg: "検索結果がありません。",
    GRID_useFilterEmptyMsg: "空の値",
    GRID_useFilterNullMsg:"Null",
    SelectBox_all: "-すべて-",
    SelectBox_choose: "選択してください",
    //CheckCombobox
    CheckCombobox_all: "すべて選択",
    CheckCombobox_choose: "選択",
    CheckCombobox_allOption_label: "すべて選択",
    CheckCombobox_label: "ラベル",
    // Calendar
    Calendar_select_year: "年度選択",
    Calendar_select_month: "月選択",
    Calendar_select_hour: "時選択",
    Calendar_valuetype_hour: "時",
    Calendar_select_minute: "分選択",
    Calendar_valuetype_minute: "分",
    Calendar_select_second: "秒選択",
    Calendar_valuetype_second: "秒",
    Calendar_previous_year: "前年",
    Calendar_previous_month: "前月",
    Calendar_next_year: "翌年",
    Calendar_next_month: "翌月",
    Calendar_open: "カレンダーから選択",
    Calendar_ok: "OK",
    Calendar_close: "閉じる",
    Calendar_cancel: "キャンセル",
    Calendar_reset: "リセット",
    Calendar_today: "現在日",
    Calendar_name: "カレンダー",
    Calendar_caption: "カレンダー",
    Calendar_summary: "カレンダー:希望の日付を選択してください。",
    Calendar_yearsuffix: "年",
    Calendar_monthnames: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
    Calendar_weekdaynames_0: "日曜日",
    Calendar_weekdaynames_1: "月曜日",
    Calendar_weekdaynames_2: "火曜日",
    Calendar_weekdaynames_3: "水曜日",
    Calendar_weekdaynames_4: "木曜日",
    Calendar_weekdaynames_5: "金曜日",
    Calendar_weekdaynames_6: "土曜日",
    Calendar_weekdaynames_short_0: "日",
    Calendar_weekdaynames_short_1: "月",
    Calendar_weekdaynames_short_2: "火",
    Calendar_weekdaynames_short_3: "水",
    Calendar_weekdaynames_short_4: "木",
    Calendar_weekdaynames_short_5: "金",
    Calendar_weekdaynames_short_6: "土",
    Calendar_tooltip: "%1年%2月%3日",
    Calendar_select_title: "選択日",
    Calendar_start: "カレンダー開始",
    Calendar_info1: "%1のcalendarValueTypeオプションが'yearMonthDate'であるため、setDateFormat APIの引数として使用できる文字列は、yyyy·MM·ddです。",
    Calendar_inof2: "%1のcalendarValueTypeオプションが'yearMonth'であるため、setDateFormat APIの引数として使用できる文字列はyyyy、MMです。",
    Calendar_info3: "%1のcalendarValueTypeオプションが'yearMonthDateHour'であるため、setDateFormat APIの引数として使用できる文字列は、yyyy·MM·dd·HHです。",
    Calendar_info4: "%1のcalendarValueTypeオプションが'yearMonthDateTime'であるため、setDateFormat APIの引数として使用できる文字列は、yyyy·MM·dd·HH·mmです。",
    //date
    Date_err_1900: "年度は1900年以上でなければなりません",
    Date_err_12: "月は12を超えることはできません。",
    Date_err_31: "日付は31を超えることはできません。",
    Date_err_29: "2月は29日までです",
    Date_err_28: "2月は28日までです",
    Date_err_30: "は30日までです",
    //multiupload
    MultiUpload_all: "すべてのファイル",
    MultiUpload_image: "画像ファイル",
    MultiUpload_add: "追加",
    MultiUpload_delete: "削除",
    MultiUpload_cancel: "キャンセル",
    MultiUpload_send: "送信",
    MultiUpload_addFile: "ファイル追加",
    MultiUpload_file: "ファイル",
    MultiUpload_size: "サイズ",
    MultiUpload_status: "ステータス",
    MultiUpload_complete: "完了",
    MultiUpload_err_fileExist: "ファイルが既に存在します。(%1)",
    MultiUpload_err_maxCountExceed: "アップロード件数が%1件に制限されています。",
    MultiUpload_err_fileSizeExceed: "アップロードファイルのサイズは%1に制限されています。",
    MultiUpload_err_HTTPExcpetion: "HTTPエラーが発生しました。(ステータスコード : %1)",
    // Pagelist
    Pagelist_first_page: "最初のページ",
    Pagelist_previous_page: "前のページ",
    Pagelist_previous: "前へ",
    Pagelist_next_page: "次のページ",
    Pagelist_next: "次へ",
    pagelist_nextList_page: "次のリストページ",
    pagelist_previousList_page: "前のリストページ",
    Pagelist_last_page: "最後のページ",
    Pagelist_selected: "%1 選択",
    Pagelist_previous_ellipsisText: "前の項目省略",
    Pagelist_next_ellipsisText: "次の項目省略",
    // slider
    Slider_warning1: "%1から%2までの値を入力する必要があります。",
    Slider_warning2: "%1から%2までの値のうち、%3ずつ増加した値を入力する必要があります。",
    Slider_range: "入力タイプ範囲",
    // Window
    Window_minimize: "ウィンドウサイズの最小化",
    Window_restore: "ウィンドウサイズの復元",
    Window_close: "ウィンドウを閉じる",
    Window_cancel: "キャンセル",
    Window_popup: "ポップアップ",
    Window_statusMsg: "ロード中です。",
    Window_popup_start: "ポップアップ開始",
    // WindowContainer
    WindowContainer_controlIcon_maximize: "現在のウィンドウを最大化/元のサイズに復元",
    WindowContainer_controlIcon_vertical: "ウィンドウを縦に並べる",
    WindowContainer_controlIcon_horizontal: "ウィンドウを横に並べる",
    WindowContainer_controlIcon_cascade: "ウィンドウを重ねて表示",
    WindowContainer_controlIcon_sequential: "碁盤目状にウィンドウを配置",
    WindowContainer_controlIcon_closeAll: "すべてのウィンドウを閉じる",
    WindowContainer_controlIcon_closeOthers: "アクティブウィンドウを除くすべてのウィンドウを閉じる",
    WindowContainer_controlIcon_windowList: "ウィンドウリストを開く",
    WindowContainer_maxNum_warning: "画面は合計%1個までしか許可されません。",
    WindowContainer_confirm_warning: "#titleの画面が存在します。既存のウィンドウを使用する場合は「確認」を、新しいウィンドウを使用する場合は「キャンセル」を選択してください",
    WindowContainer_maximize: "ウィンドウサイズ最大化",
    WindowContainer_restore: "ウィンドウサイズの復元",
    WindowContainer_next: "前のウィンドウ",
    WindowContainer_previous: "次のウィンドウ",
    WindowContainer_empty_status: "ウィンドウがない状態",
    WindowContainer_default_view_status: "現在の基本表示状態",
    WindowContainer_horizontal_align: "ウィンドウの水平方向の配置を表示",
    WindowContainer_horizontal_align_status: "現在のウィンドウの水平方向の整列表示状態",
    WindowContainer_vertical_align: "ウィンドウの垂直整列表示",
    WindowContainer_vertical_align_status: "現在のウィンドウの垂直方向の整列表示状態",
    WindowContainer_cascade_align: "カスケード表示",
    WindowContainer_cascade_align_status: "現在のカスケード表示状態",
    WindowContainer_tiled_align: "タイル状にウィンドウを配置",
    WindowContainer_tiled_align_status: "現在のタイル状ウィンドウ配置状態",
    WindowContainer_windowList: "ウィンドウリスト",
    WindowContainer_fix_dialog: "ダイアログを固定",
    WindowContainer_fix_dialog_set: "ダイアログボックスの固定が選択されました",
    WindowContainer_fix_dialog_unset: "ダイアログボックスの固定が選択されていません",
    WindowContainer_close_dialog: "ダイアログを閉じる",
    WindowContainer_custom: "カスタム",
    WindowContainer_dualMonitors: "デュアルモニターで表示",
    WindowContainer_multiView: "マルチビューで表示",
    WindowContainer_share: "共有",
    WindowContainer_minimizeSize_status: "現在の最小化サイズ",
    WindowContainer_defaultSize_status: "現在の基本サイズ",
    WindowContainer_maximizeSize_status: "現在の最大化サイズ",
    // WidgetContainer
    WidgetContainer_setCols_warning: "無効なcolsです。",
    WidgetContainer_maximize: "最大化ボタン",
    WidgetContainer_minimize: "最小化ボタン",
    WidgetContainer_minimizeSize_status: "現在の最小化サイズ",
    WidgetContainer_defaultSize_status: "現在の基本サイズ",
    WidgetContainer_maximizeSize_status: "現在の最大化サイズ",
    WidgetContainer_fix: "固定",
    WidgetContainer_fix_set: "選択済み",
    WidgetContainer_fix_unset: "解除済み",
    WidgetContainer_close: "閉じる",
    // DatePicker
    DatePicker_yearSuffix: "年",
    DatePicker_monthNames: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
    DatePicker_dateSuffix: "日",
    DatePicker_ampm: "午前,午後",
    DatePicker_select_year : "年度選択",
    DatePicker_select_month : "月選択",
    DatePicker_select_date : "日選択",
    DatePicker_select_ampm : "午前午後選択",
    DatePicker_select_hour : "時間選択",
    DatePicker_select_minutes : "分選択",
    // chart
    Chart_context_chartType: "チャートタイプ",
    Chart_context_chartOption: "チャートオプション",
    Chart_context_chartStyle: "チャートの書式",
    Chart_context_seriseOption: "系列オプション",
    Chart_main_axis: "主軸",
    Chart_auxiliary_axis: "補助軸",
    Chart_warning_msg1: "データが正しくありません",
    Chart_warning_load_default_version: "デフォルトバージョン％1としてロードされます",
    Chart_warning_incorrect_chart_version: "チャートのバージョンが正しくありません",
    Chart_warning_no_resource: "チャートバージョンに対応するリソースがありません",
    // tabControl
    TabControl_maxNum_warning: "タブ数は最大%1個まで許可されます。",
    TabControl_close: "閉じる",
    TabControl_close_all: "すべて閉じる",
    TabControl_right_corner: "右側の角の画像",
    TabControl_left_corner: "左隅の画像",
    TabControl_warning1: "[#title]タブが存在します。既存のタブを使用する場合は「確認」を、新しいタブを作成する場合は「キャンセル」を選択してください",
    TabControl_previous_tab: "前のタブ",
    TabControl_next_tab: "次のタブ",
    TabControl_tab_list: "タブリスト",
    TabControl_selected: "%1 選択済み",
    //autoComplete
    AutoComplete_addItem_invalid: "該当itemのvalue値が%1の%2番目の位置に既に存在します。value値は一意である必要があります。",
    AutoComplete_all: "-全体-",
    AutoComplete_choose: "選択",
    AutoComplete_inputFormat: "入力書式ラベル",
    AutoComplete_label: "オートコンプリート",
    
    // grid
    Grid_sort_none: "並べ替え解除",
    Grid_sort_asc: "昇順並べ替え",
    Grid_sort_desc: "降順並べ替え",
    Grid_sort_asc_info: "%1 セルで昇順に並べ替え",
    Grid_sort_desc_info: "%1 セルで降順に並べ替え",
    Grid_filter_title: "ユーザー定義フィルター",
    Grid_filter_search: "検索",
    Grid_filter_search_label: "検索条件",
    Grid_filter_condition1: "開始文字",
    Grid_filter_condition2: "除外する開始文字",
    Grid_filter_condition3: "末尾文字",
    Grid_filter_condition4: "除外する末尾文字",
    Grid_filter_condition5: "含む",
    Grid_filter_condition6: "含まない",
    Grid_filter_condition7: "= (メタ文字使用)",
    Grid_filter_info_Label1: "?記号を使用して1文字を表すことができます。",
    Grid_filter_info_Label2: "* 記号を使用して複数の文字を表すことができます。",
    Grid_filter_confirm: "確認",
    Grid_filter_cancel: "キャンセル",
    Grid_filter_reset: "リセット",
    Grid_filter_button: "フィルターボタン",
    Grid_Customized_Filter: "カスタムフィルター",
    Grid_column_hide: "選択列を非表示",
    Grid_column_showAll: "全ての列の非表示を解除",
    Grid_column_fix: "選択カラム固定",
    Grid_column_unfix: "全列の固定解除",
    Grid_column_adjustWidth: "選択列のサイズを自動調整",
    Grid_column_adjustAuto: "全カラムサイズ自動調整",
    Grid_column_adjustAuto_none: "全カラムサイズの自動調整を解除",
    Grid_fold_all: "全体グループ折りたたみ",
    Grid_unfold_all: "全体グループを展開",
    Grid_ungroup_all: "全体グループ解除",
    Grid_ungroup: "選択列のグループ解除",
    Grid_group: "選択カラムグループ",
    Grid_noResultMessage: "検索結果がありません。",
    Grid_scrollMsg: "画面更新中です...",
    Grid_all: "-すべて-",
    Grid_checked_all: "全体選択",
    Grid_incorrect_inputType: "セルのinputTypeが正しくありません。",
    Grid_warning1: "選択した列はチェックボックスではありません。",
    Grid_warning2: "入力データの型が正しくありません。true/falseのブール型で入力してください",
    Grid_warning3: "inputTypeがcheckboxまたはradioではありません。",
    Grid_warning4: "[%1] [%2] 設定を変更する機能はまだサポートされていません",
    Grid_warning5: "%1 adaptiveをサポートしないGridです。",
    Grid_warning6: "%1 groupbyが有効になっているため、lazyDrawHiddenColumn属性が無効になりました。",
    Grid_warning7: "%1 : rowSpanがあるため、lazyDrawHiddenColumn属性が無効になりました。",
    Grid_warning8: "セルの数が制限サイズを超えました。\n制限数：%1",
    Grid_warning9: "送信データが制限サイズを超えました。\n制限サイズ：%1 バイト",
    Grid_warning10: "行数が制限サイズを超えました。\n制限数：%1",
    Grid_caption: "を示す表",
    Grid_caption2: "は",
    Grid_caption_shortcut: "CTRLキーとENDキーを同時に押すと、フォーカスがテーブルの最後のセルに移動します。",
    Grid_footer_caption: "合計を表す表",
    Grid_title: "選択",
    Grid_title_not_choose: "選択しない",
    Grid_title_partial: "部分選択",
    Grid_button: "ボタン",
    Grid_select: "セレクト",
    Grid_calendar: "カレンダー",
    Grid_secret: "シークレット",
    Grid_text: "テキスト",
    Grid_link: "リンク",
    Grid_autoComplete: "オートコンプリート",
    Grid_more_Button: "リストをもっと見る",
    Grid_rowStatus_initialValue: "初期値", // R
    Grid_rowStatus_update: "更新", // U
    Grid_rowStatus_insert: "挿入", // C
    Grid_rowStatus_delete: "削除", // D
    Grid_rowStatus_D_After_C: "挿入後削除", // V
    Grid_cases: "件",
    Grid_dom_start: "グリッド開始",
    Grid_dom_end: "グリッド終了",
    Grid_row: "行",
    Grid_column: "列",
    Grid_groupby_count: "件",
    //fwGanttChart
    fwGanttChart_ampm: "午前,午後",
    fwGanttChart_yearSuffix: "年",
    fwGanttChart_monthSuffix: "月",
    fwGanttChart_dateSuffix: "日",
    fwGanttChart_timeGap3Label: "深夜,午前3時,午前6時,午前9時,正午,午後3時,午後6時,午後9時",
    fwGanttChart_timeGap6Label: "深夜,午前6時,正午,午後6時",
    fwGanttChart_quarterNames: "第1四半期·第2四半期·第3四半期·第4四半期",
    fwGanttChart_monthNames: "1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月",
    //mapchart
    Map_name_39: "済州",
    Map_name_38: "慶尚南道",
    Map_name_36: "全羅南道",
    Map_name_35: "全羅北道",
    Map_name_34: "忠南",
    Map_name_33: "忠北",
    Map_name_32: "カンウォン",
    Map_name_31: "京畿",
    Map_name_29: "セジョン",
    Map_name_26: "ウルサン",
    Map_name_25: "テジョン",
    Map_name_24: "光州",
    Map_name_22: "テグ",
    Map_name_21: "釜山",
    Map_name_11: "ソウル",
    Map_name_37: "慶尚北道",
    Map_name_23: "インチョン",
    // upload
    Upload_ignore_spaces: "空白無視",
    Upload_include_spaces: "空白を含む",
    Upload_advanced: "詳細設定",
    Upload_hidden_values: "非表示値の有無",
    Upload_include: "含む",
    Upload_not_include: "未含む",
    Upload_fill_hidden: "非表示項目の入力",
    Upload_sheet_no: "シート No",
    Upload_starting_row: "開始行",
    Upload_starting_col: "開始col",
    Upload_header: "ヘッダーの有無",
    Upload_footer: "フッターの有無",
    Upload_file: "ファイルアップロード",
    Upload_file_title: "ファイルアップロード",
    Upload_file_header: "ファイルアップロード",
    Upload_file_choose: "ファイル選択",
    Upload_file_span: "選択されたファイルなし",
    Upload_fill: "塗りつぶし",
    Upload_ignore: "無視",
    Upload_pwd: "パスワード",
    Upload_msg1: "ファイルアップロードのための一時フレーム",
    Upload_msg2: "ファイルサイズが制限容量を超えました。",
    Upload_msg3: "正常に処理されませんでした。",
    Upload_msg4: "FileTypeに一致しないファイルの拡張子です。",
    Upload_msg5: "グリッドへの反映に失敗しました",
    Upload_msg6: "データ収集中..",
    Upload_msg7: "データ変換完了",
    Upload_msg8: "パスワードが一致しません。",
    Upload_msg9: "許可されていない拡張子です。",
    Upload_msg10: "DRMとの連携時にエラーが発生しました。",
    Upload_msg11: "アップロード制限件数を超えました。",
    Upload_msg12: "無効なExcel形式です。",
    Upload_msg13: "無効なセル書式です。",
    Upload_msg14: "アップロードセル数制限を超えました。",
    Upload_msg15: "ファイルが暗号化されています。",
    Upload_msg16: "Excel 5.0/7.0はサポートしていません。",
    Upload_msg17: "指定されたシートが存在しません。",
    Upload_msg18: "書き込み専用ファイルまたは読み取り不可能なファイルです。",
    Upload_warning1: "セキュリティ上の問題で使用できない機能です。",
    //datalist
    DataList_msg1: "処理中に予期しないエラーが発生しました。",
    DataList_msg2: "ユーザー定義プロバイダークラスが見つかりません。",
    DataList_msg3: "ユーザー定義プロバイダーとの連携データの生成中にエラーが発生しました。",
    DataList_msg4: "ステータスがfalseに設定されたため、処理が終了しました。",
    DataList_msg5: "受信可能な最大行数を超えたため、処理が中断されました。",
    //itemTable
    itemTable_confirm: "選択適用",
    itemTable_cancel: "選択解除",
    //pivot
    Pivot_canNotMoveToHiddenList: "非表示領域に移動できません。",
    Pivot_sum: "合計",
    Pivot_average: "平均",
    Pivot_count: "件数",
    Pivot_min: "最小値",
    Pivot_max: "最大値",
    Pivot_renderError: "ピボットテーブルのレンダリング中にエラーが発生しました。",
    Pivot_computeError: "ピボットテーブルのデータを計算中にエラーが発生しました。",
    Pivot_uiRenderError: "ピボットテーブルのUIをレンダリング中にエラーが発生しました。",
    Pivot_dragError: "合計は値エリアにドラッグできません。",
    Pivot_selectAll: "全体選択",
    Pivot_selectNone: "全体解除",
    Pivot_tooMany: "(リストで表示する値が多すぎます。)",
    Pivot_filterResults: "フィルタリングする項目を入力してください。",
    Pivot_totals: "合計",
    Pivot_vs: "vs",
    Pivot_by: "by",
    Pivot_apply: "適用",
    Pivot_cancel: "閉じる",
    //slideHide
    SlideHide_btnHide: "折りたたむ",
    SlideHide_btnShow: "展開",
    SlideHide_btnToggle: "展開·縮小ボタン",
    //switch
    Switch_btnPrev: "前へ",
    Switch_btnNext: "次へ",
    Switch_pagination_ariaLabel: "%1個中の%2番目のスライドに移動",
    Switch_case_ariaRoledesc: "スライド",
    Switch_case_ariaLabel: "%1個中%2番目",
    Switch_selected_pagination: "選択済み",
    //searchbox
    Searchbox_ariaLabel: "検索フォーム",
    Searchbox_resetButton_ariaLabel: "入力内容削除",
    //treeview
    Treeview_iconNaviAriaLabel: "展開・折りたたみボタン",
    Treeview_warning1: "treeviewを動的に処理する場合は、dynamicAppend='true'に設定することをお勧めします。",
    Treeview_warning2: "treeviewのアコーディオンモードでは%1 APIをサポートしていません。",
    //multiselect
    multiselect_ariaLabel: "複数選択領域",
    multiselect_item_selected_ariaLabel: "%1 , 選択",
    multiselect_item_deselected_ariaLabel: "%1 , 選択されていません",
    //editor
    Editor_currentChar: "文字",
    Editor_maxChar_warning: "%1文字を超えることはできません。",
    Editor_warning_load_default_version: "デフォルトバージョン％1としてロードされます",
    Editor_warning_incorrect_editor_version: "エディタのバージョンが正しくありません",
    Editor_warning_no_resource: "エディタバージョンに対応するリソースがありません",
    Editor_ariaLabel: "リッチテキストエディタ,ヘルプは ALT 0 を押してください",
    //scheduleCalendar
    scheduleCalendar_schedule: "スケジュール",
    //performance
    Performance_step1 : "ブラウザのURL呼び出しを開始する瞬間からブートローダーのロードが完了するまでにかかる時間です。ブートローダーはウェブスクエアエンジンの初期起動に不可欠な要素です",
    Performance_step2 : "BootLoaderの実行完了からウェブスクエアエンジン全体のロードが完了するまでにかかる時間です。",
    Performance_step3 : "ウェブスクエアエンジンのロード完了からウェブスクエアページファイル、共通JS及びCSSファイルのロードが完了するまでにかかる時間です。",
    Performance_step4 : "リソース（ウェブスクエアページファイル、共通JS及びCSSファイル）のロード完了からウェブスクエアコンポーネントオブジェクトが生成されるまでにかかる時間です。",
    Performance_step5 : "コンポーネントオブジェクトの生成完了からコンポーネントのレンダリングが完了するまでにかかる時間です。",
    Performance_step6 : "コンポーネントのレンダリング完了からコンポーネントの前処理作業が完了するまでにかかる時間です。",
    Performance_step7 : "コンポーネントの前処理作業完了からコンポーネントの初期化作業が完了するまでにかかる時間です。",
    Performance_step8 : "コンポーネントの初期化作業完了からinitScriptの実行が完了するまでにかかる時間です。ただし、initScript内の非同期処理時間は除外されます。",
    Performance_step9 : "initScriptの実行完了からonpageloadイベントの実行が完了するまでにかかる時間です。ただし、onpageload内の非同期処理時間は除外されます。",
    Performance_step10 : "onpageloadの実行完了からpostScriptの実行が完了するまでにかかる時間です。ただし、postScript内の非同期処理時間は除外されます。この段階でウェブスクエアの初期化が完了しますが、非同期処理時間は除外されます。",
    Performance_event : "この測定指標は、イベントハンドラがイベントの開始から完了までに実行するのにかかる時間を測定します。ハンドラ内の非同期部分は除外されます。特定のイベントタイプに関する詳細については、type属性値を参照してください。",
    Performance_submission_start : "submissionの開始時点からcustomHandler関数の呼び出しが完了するまでにかかる時間です。ただし、customHandlerが非同期の場合は、非同期処理にかかる時間は除外されます。",
    Performance_submission_end_replaceAll : "replace='all'モードの場合、submissionの開始時点からsubmission処理が完了するまでにかかる時間です。これには<form>タグの生成及びform.submitを通じてsubmissionを処理する時間を含みます。",
    Performance_submission_step1 : "submissionの実行からネットワークにURLリクエストを送信する直前までにかかる時間です。",
    Performance_submission_end_error_script : "submissionの実行開始からsubmission処理中にエラーが発生して中断されるまでにかかる時間です。",
    Performance_submission_step2 : "submission URLに対するネットワークリクエストを送信した時点からネットワーク応答が到着し、commonResponseHandlerコールバック関数が開始されるまでにかかる時間です。",
    Performance_submission_end_error_network : "submission urlに対するネットワークリクエストを送信した時点から、ネットワーク応答の失敗によりsubmissionが強制終了されるまでにかかる時間です。この測定指標にはネットワークステータスコード(%1)が含まれます。",
    Performance_submission_step3 : "submissionのcallback関数commonResponseHandlerを開始する瞬間からsubmissionのref属性とtarget属性の処理完了までにかかる時間です。",
    Performance_submission_end_ok : "submissionのref属性とtarget属性の処理完了から、ユーザーイベントonsubmitdoneの実行完了までにかかる時間です。これはsubmission処理が完了したことを意味します。",
    Performance_wframe_step1: "wframeの生成からウェブスクエアページファイルのロード及びDOMレンダリング（toHTML）完了までにかかる時間です。",
    Performance_wframe_step2: "wframeのinitScript、onpageload、postScriptイベントの実行時間です。これはwframeの処理が完了したことを示します。総経過時間はstep1とstep2の合計です。",
    //accessibility
    Accssibility_btn_aria_label_windowContainer: "ウィンドウを閉じる"
    //dragghost
    Drag_no_data: "データなし"
};
