var WebSquareLang = {

    //Actions.js
    E_Actions_fileuploadPopupName: "파일업로드 : %1",
    //date.js
    E_date_ShouldBeyyMMddFormat: "입력값은 yyyyMMdd형식이어야 합니다. 입력값 : %1",
    E_date_month_ShouldBeyyMMFormat: "입력값은 yyyyMM형식이어야 합니다. 입력값 : %1",
    E_date_hour_ShouldBeyyMMddHHFormat: "입력값은 yyyyMMddHH형식이어야 합니다. 입력값 : %1",
    E_date_minute_ShouldBeyyMMddmmFormat: "입력값은 yyyyMMddHHmm형식이어야 합니다. 입력값 : %1",
    E_date_minute_ShouldBeHHmmssFormat: "입력값은 HHmmss형식이어야 합니다. 입력값 : %1",
    E_date_minute_ShouldBeHHmmFormat: "입력값은 HHmm형식이어야 합니다. 입력값 : %1",
    E_date_ShouldBeNumberFormat: "입력값은 숫자형식이어야 합니다. 입력값 : %1",
    E_date_YearRange: "연도는 %1부터 %2사이 값이어야 합니다. 입력값 : %3",
    E_date_MonthRange: "월은 %1부터 %2사이 값이어야 합니다. 입력값 : %3",
    E_date_DayRange: "일은 %1부터 %2사이 값이어야 합니다. 입력값 : %3",
    E_date_HourRange: "시간은 %1부터 %2사이 값이어야 합니다. 입력값 : %3",
    E_date_MinuteRange: "분은 %1부터 %2사이 값이어야 합니다. 입력값 : %3",
    E_date_SecondRange: "초는 %1부터 %2사이 값이어야 합니다. 입력값 : %3",
    //exception.js
    E_exception_ErrorOccursSeeLog: "작업 도중 오류가 발생하였습니다.\n%1",
    E_exception_IERuntimeError: "Runtime Error\n    줄 No.    : %1 \n    문자 : %2\n    코드 : %3\n    URL : %4\n    오류 : %5\n    원본 : %6",
    E_exception_FFRuntimeError: "Runtime Error\n    줄 No.    : %1 \n    URL : %2 \n    오류 : %3 \n    원본 : %4 ",
    //form.js
    E_form_TimeKeyUpWrongHourFormat: "시간 입력이 잘못되었습니다.",
    E_form_TimeKeyUpWrongMinuteFormat: "분 입력이 잘못되었습니다.",
    //initializer.js
    E_initializer_XMLLoadFailError: "W2X 파일을 읽어들이는데 실패했습니다. 경로를 확인하세요. URL [ %1 ]",
    E_initializer_XMLLoadFailError1: "읽어들인 W2X 파일을 처리하는데 실패했습니다. URL [ %1 ]",
    //logger.js
    E_logger_ContextmenuSeeLog: "로그 보기",
    E_logger_ContextmenuSeePerformanceLog: "성능로그 보기",
    E_logger_ContextmenuSeeAddress: "주소",
    E_logger_ContextmenuSeeQR: "QR 보기",
    E_logger_ContextmenuSeeSource: "소스 보기",
    E_logger_ContextmenuSeeCollection: "dataCollection 보기",
    E_logger_ContextmenuSeeInstance: "인스턴스 보기",
    E_logger_ContextmenuSeeFiddle: "Fiddle 보기",
    E_logger_ContextmenuSeeSubmission: "submission 보기",
    E_logger_ContextmenuStopDebugOnScreen: "현재 화면 디버그 중단",
    E_logger_ContextmenuStartDebugOnScreen: "현재 화면 디버그 실행",
    E_logger_ContextmenuStopDebugOnSystem: "전체 시스템 디버그 중단",
    E_logger_ContextmenuStartDebugOnSystem: "전체 시스템 디버그 실행",
    E_logger_ContextmenuStartEventDebug: "현재 화면 이벤트 출력 실행",
    E_logger_ContextmenuStopEventDebug: "현재 화면 이벤트 출력 중단",
    E_logger_ContextmenuPrint: "인쇄",
    E_logger_ContextmenuRefresh: "새로고침",
    E_logger_ContextmenuPageReload: "페이지 초기화",
    E_logger_ContextmenuPageReloadWframe: "wframe 초기화",
    E_logger_ContextmenuBrowserReload: "브라우저 초기화",
    E_logger_ContectmenuFileInfo: "File 정보",
    E_logger_ContextmenuVersion: "Version 정보",
    E_logger_EnterPassword: "비밀번호를 입력하세요.",
    E_logger_IncorrectPassword: "비밀번호가 일치하지 않습니다.",
    E_logger_ObjectDisabled: "객체가 disable되어 있습니다.",
    E_logger_UsedXSLInfo: "사용한 XSL : %1",
    E_logger_NoUsedXSLInfo: "객체를 그리는데 사용한 XSL이 없습니다.",
    E_logger_InnerBlindObject: "[내부 구조를 볼 수 없는 Object입니다.]\n\n",
    E_logger_InitDueToOverline: "%1 [%2] 로그가 500줄 이상 되서 로그를 초기화 합니다.",
    E_logger_ObjectInfo: "Object 정보",
    E_logger_XSLInfo: "XSL 정보",
    E_logger_changeClientName: "원격 디버깅에 사용할 Client Name를 입력하세요.",
    //Model.js
    E_Model_NoChildNodeOfInstance: "해당 instance의 child node가 존재하지 않습니다.",
    //ModelUtil.js
    E_ModelUtil_NoSubmissionObjectWithID: "submission 객체[ %1 ]가 존재하지 않습니다.",
    E_ModelUtil_NoSubmissionObject: "submission 객체가 존재하지 않습니다.",
    //net.js
    E_net_PopupBlocked: "팝업이 차단되었습니다.",
    //Parser.js
    E_Parser_MoreThanOneHeadError: "WebSquare의 Head는 하나만 허용됩니다. 현재 XML은 Head가 '%1'개 입니다.",
    E_Parser_MoreThanOneBodyError: "WebSquare의 Body는 하나만 허용됩니다. 현재 XML은 Body가 '%1'개 입니다.",
    //WebSquareDocument.js
    E_WebSquareDocument_MoreThanOneBodyError: "WebSquare의 Body는 하나만 허용됩니다. 현재 XML은 Body가 '%1'개 입니다.",
    //xml.js
    E_xml_XMLUnsupportedBrowser: "XML을 지원하지 않는 브라우저 입니다.",
    E_xml_ErrorOccurLoadingXMLWithURL: "XML을 Loading하던 중 Error가 발생했습니다.\n\nURL : %1",
    E_xml_ErrorOccurLoadingXML: "XML을 Loading하던 중 Error가 발생했습니다.\n",
    E_xml_ErrorOccurParsingXML: "XML을 Parsing하던 중 Error가 발생했습니다.\n",
    //core.js
    E_core_AjaxUnsupportedBrowser: "Ajax를 지원하지 않는 브라우저 입니다.",
    E_core_NoPluginError: "Plugin[ %1 ]이 존재하지 않습니다.",
    E_core_NoModuleError: "Module[ %1 ]이 존재하지 않습니다.",
    //event.js
    E_event_AddEventError: "id가 없는 HTML객체가 존재하거나 현재 버전에서는 지원하지 않는 Action[ %1 ] 이 사용되었습니다.",
    E_dc_duplicated_Msg: "id[%1]가 중복되었습니다. 기존에 있던 %2을 삭제하고 새로 생성합니다.",
    E_comp_duplicated_Msg: "id[%1] 가 중복사용되었습니다. 소스코드를 확인하세요.",
    //logMsg.html
    E_logMsg_LogInfo: "Log 정보입니다.",
    E_logMsg_LogAutoRenewal: "자동갱신 중",
    E_logMsg_LogAutoRenewalStop: "자동갱신 중단",
    //QR.html
    E_viewQR_title: "QR Information.",
    //viewSource.html
    E_viewSource_title: "Source Information.",
    //viewColleciton.html
    E_viewCollection_title: "Collection Information.",
    //viewInstance.html
    E_viewInstance_title: "Instance Information.",
    //viewSubmission.html
    E_viewSubmission_title: "Submission Information.",
    //debugMsg.html
    E_debugMsg_DebugInfo: "Debug 정보입니다.",
    //processMsg.html
    E_processMsg_Processing: "처리 중입니다.",
    //errorMsg.html
    E_errorMsg_ErrorInfo: "Error 정보입니다.",
    //deprecated
    E_deprecated_sync: "동기(synchronous) 통신은 성능 문제로 인해 사용을 권장하지 않습니다. 비동기(asynchronous) 통신을 사용할 것을 권장합니다.[%1]",
    //validator
    V_error_minLength: "최소 %1 자리 이상 입력해야 합니다.",
    V_error_maxLength: "최대 %1 자리 이상 입력할 수 없습니다.",
    V_error_maxFloatLength: "최대 정수 %1 자리, 소수 %2 자리 이상 입력할 수 없습니다.",
    V_error_minByteLength: "최소 %1 byte 이상 입력해야 합니다.",
    V_error_maxByteLength: "최대 %1 byte 이상 입력할 수 없습니다.",
    V_error_validCondition: "Validator의 수행 조건을 만족하지 못했습니다.",
    V_error_no_valiator: "Validator가 존재하지 않거나 객체가 아닙니다.",
    V_error_mandatory: "필수 입력 항목입니다",
    V_error_allowChar: "허용된 문자열은 %1 입니다",
    V_error_ignoreChar: "허용되지 않은 문자열은 %1 입니다",
    V_error_date: "날짜 형식이 잘못 되었습니다.",
    V_error_float: "실수 형식이 잘못 되었습니다.",
    AllText: "전체",
    //formatter
    F_dateFormat_daynames_abbr: "월,화,수,목,금,토,일",
    F_dateFormat_daynames_full: "월요일,화요일,수요일,목요일,금요일,토요일,일요일",
    IC_Mask: "yyyy-MM-dd",
    IC_Delimiter: "-",
    IC_invalidCalendarSelect: "날짜 형식이 잘못 되었습니다.",
    GRID_noResultMsg: "조회결과가 없습니다.",
    GRID_useFilterEmptyMsg: " 빈 값",
    SelectBox_all: "-전체-",
    SelectBox_choose: "-선택-",
    //CheckCombobox
    CheckCombobox_all: "전체 선택",
    CheckCombobox_choose: "선택",
    CheckCombobox_allOption_label: "전체선택",
    CheckCombobox_label: "레이블",
    // Calendar
    Calendar_select_year: "연도 선택",
    Calendar_select_month: "달 선택",
    Calendar_select_hour: "시 선택",
    Calendar_valuetype_hour: "시",
    Calendar_select_minute: "분 선택",
    Calendar_valuetype_minute: "분",
    Calendar_select_second: "초 선택",
    Calendar_valuetype_second: "초",
    Calendar_previous_year: "이전 해",
    Calendar_previous_month: "이전 달",
    Calendar_next_year: "다음 해",
    Calendar_next_month: "다음 달",
    Calendar_open: "달력에서 선택",
    Calendar_ok: "확인",
    Calendar_close: "닫기",
    Calendar_cancel: "취소",
    Calendar_reset: "리셋",
    Calendar_today: "현재일",
    Calendar_name: "달력",
    Calendar_caption: "달력",
    Calendar_summary: "달력:원하는 날짜를 선택하세요.",
    Calendar_yearsuffix: "년",
    Calendar_monthnames: "1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월",
    Calendar_weekdaynames_0: "일요일",
    Calendar_weekdaynames_1: "월요일",
    Calendar_weekdaynames_2: "화요일",
    Calendar_weekdaynames_3: "수요일",
    Calendar_weekdaynames_4: "목요일",
    Calendar_weekdaynames_5: "금요일",
    Calendar_weekdaynames_6: "토요일",
    Calendar_weekdaynames_short_0: "일",
    Calendar_weekdaynames_short_1: "월",
    Calendar_weekdaynames_short_2: "화",
    Calendar_weekdaynames_short_3: "수",
    Calendar_weekdaynames_short_4: "목",
    Calendar_weekdaynames_short_5: "금",
    Calendar_weekdaynames_short_6: "토",
    Calendar_tooltip: "%1년 %2월 %3일",
    Calendar_select_title: "선택일",
    Calendar_start: "달력 시작",
    Calendar_info1: "%1 의 calendarValueType옵션이 'yearMonthDate'이므로 setDateFormat API의 인자로 사용할 수 있는 문자열은 yyyy, MM, dd입니다.",
    Calendar_inof2: "%1 의 calendarValueType옵션이 'yearMonth'이므로 setDateFormat API의 인자로 사용할 수 있는 문자열은 yyyy, MM입니다.",
    Calendar_info3: "%1 의 calendarValueType옵션이 'yearMonthDateHour'이므로 setDateFormat API의 인자로 사용할 수 있는 문자열은 yyyy, MM, dd, HH입니다.",
    Calendar_info4: "%1 의 calendarValueType옵션이 'yearMonthDateTime'이므로 setDateFormat API의 인자로 사용할 수 있는 문자열은 yyyy, MM, dd, HH, mm입니다.",
    //date
    Date_err_1900: "년도는 1900 년도 이상이어야 합니다",
    Date_err_12: "달은 12 를 초과할 수 없습니다.",
    Date_err_31: "날짜는 31 을 초과할 수 없습니다.",
    Date_err_29: "2월은 29일까지 입니다",
    Date_err_28: "2월은 28일까지 입니다",
    Date_err_30: "은 30일까지 입니다",
    //multiupload
    MultiUpload_all: "모든 파일",
    MultiUpload_image: "그림파일",
    MultiUpload_add: "추가",
    MultiUpload_delete: "삭제",
    MultiUpload_cancel: "취소",
    MultiUpload_send: "전송",
    MultiUpload_addFile: "파일추가",
    MultiUpload_file: "파일",
    MultiUpload_size: "크기",
    MultiUpload_status: "상태",
    MultiUpload_complete: "완료",
    MultiUpload_err_fileExist: "파일이 이미 있습니다. (%1)",
    MultiUpload_err_maxCountExceed: "업로드 건수가 %1건으로 제한되어 있습니다.",
    MultiUpload_err_fileSizeExceed: "업로드 파일 크기는 %1 로 제한되어 있습니다.",
    MultiUpload_err_HTTPExcpetion: "HTTP 오류가 발생했습니다. (상태코드 : %1)",
    // Pagelist
    Pagelist_first_page: "첫 페이지",
    Pagelist_previous_page: "이전 페이지",
    Pagelist_previous: "이전",
    Pagelist_next_page: "다음 페이지",
    Pagelist_next: "다음",
    Pagelist_nextList_page: "다음 목록",
    Pagelist_previousList_page: "이전 목록",
    Pagelist_last_page: "마지막 페이지",
    Pagelist_selected: "%1 선택",
    // slider
    Slider_warning1: "%1 에서 %2 사이의 값을 입력해야 합니다.",
    Slider_warning2: "%1 에서 %2 까지의 값들 중 %3 씩 증가한 값을 입력해야 합니다.",
    Slider_range: "입력 유형 범위",
    // Window
    Window_minimize: "창 사이즈 최소화",
    Window_restore: "창 사이즈 복원",
    Window_close: "창닫기",
    Window_cancel: "취소",
    Window_popup: "팝업",
    Window_statusMsg: "로딩중입니다.",
    Window_popup_start: "팝업 시작",
    // WindowContainer
    WindowContainer_controlIcon_maximize: "현재 창 최대화/이전 크기로 복원",
    WindowContainer_controlIcon_vertical: "창 세로 정렬",
    WindowContainer_controlIcon_horizontal: "창 가로 정렬",
    WindowContainer_controlIcon_cascade: "계단식 창 배열",
    WindowContainer_controlIcon_sequential: "바둑판식 창 배열",
    WindowContainer_controlIcon_closeAll: "모든 창 닫기",
    WindowContainer_controlIcon_closeOthers: "활성 창을 제외한 모든 창 닫기",
    WindowContainer_controlIcon_windowList: "윈도우 목록 열기",
    WindowContainer_maxNum_warning: "화면은 총 %1개까지만  허용됩니다.",
    WindowContainer_confirm_warning: "#title 화면이 존재합니다. 기존의 창을 사용하시려면 '확인'을 새로운 창을 사용하시려면 '취소'를 선택하세요",
    WindowContainer_maximize: "창 사이즈 최대화",
    WindowContainer_restore: "창 사이즈 복원",
    WindowContainer_next: "이전창",
    WindowContainer_previous: "다음창",
    WindowContainer_empty_status: "창이 없는 상태",
    WindowContainer_default_view_status: "현재 기본 보기 상태",
    WindowContainer_horizontal_align: "창 가로 정렬 보기",
    WindowContainer_horizontal_align_status: "현재 창 가로 정렬 보기 상태",
    WindowContainer_vertical_align: "창 세로 정렬 보기",
    WindowContainer_vertical_align_status: "현재 창 세로 정렬 보기 상태",
    WindowContainer_cascade_align: "계단식 창 배열",
    WindowContainer_cascade_align_status: "현재 계단식 창 배열 상태",
    WindowContainer_tiled_align: "바둑판식 창 배열",
    WindowContainer_tiled_align_status: "현재 바둑판식 창 배열 상태",
    WindowContainer_windowList: "창 목록",
    WindowContainer_fix_dialog: "대화상자 고정",
    WindowContainer_fix_dialog_set: "대화상자 고정 선택됨",
    WindowContainer_fix_dialog_unset: "대화상자 고정 선택되지 않음",
    WindowContainer_close_dialog: "대화상자 닫기",
    WindowContainer_custom: "사용자정의",
    WindowContainer_dualMonitors: "듀얼 모니터로 보기",
    WindowContainer_multiView: "멀티 뷰로 보기",
    WindowContainer_share: "공유하기",
    WindowContainer_minimizeSize_status: "현재 최소화 크기",
    WindowContainer_defaultSize_status: "현재 기본 크기",
    WindowContainer_maximizeSize_status: "현재 최대화 크기",
    // WidgetContainer
    WidgetContainer_setCols_warning: "유효하지 않는 cols입니다.",
    WidgetContainer_maximize: "최대화 버튼",
    WidgetContainer_minimize: "최소화 버튼",
    WidgetContainer_minimizeSize_status: "현재 최소화 크기",
    WidgetContainer_defaultSize_status: "현재 기본 크기",
    WidgetContainer_maximizeSize_status: "현재 최대화 크기",
    WidgetContainer_fix: "고정",
    WidgetContainer_fix_set: "선택됨",
    WidgetContainer_fix_unset: "해제됨",
    WidgetContainer_close: "닫기",
    // DatePicker
    DatePicker_yearSuffix: "년",
    DatePicker_monthNames: " 1월, 2월, 3월, 4월, 5월, 6월, 7월, 8월, 9월,10월,11월,12월",
    DatePicker_dateSuffix: "일",
    DatePicker_ampm: "오전,오후",
    DatePicker_select_year : "연도 선택",
    DatePicker_select_month : "월 선택",
    DatePicker_select_date : "일 선택",
    DatePicker_select_ampm : "오전오후 선택",
    DatePicker_select_hour : "시간 선택",
    DatePicker_select_minutes : "분 선택",
    // chart
    Chart_context_chartType: "차트 타입",
    Chart_context_chartOption: "차트 옵션",
    Chart_context_chartStyle: "차트 서식",
    Chart_context_seriseOption: "계열 옵션",
    Chart_main_axis: "주축",
    Chart_auxiliary_axis: "보조축",
    Chart_warning_msg1: "데이터가 올바르지 않습니다",
    Chart_warning_load_default_version: "기본 버전인 %1로 로딩됩니다",
    Chart_warning_incorrect_chart_version: "차트 버전이 올바르지 않습니다",
    Chart_warning_no_resource: "차트 버전에 해당하는 리소스가 없습니다",
    // tabControl
    TabControl_maxNum_warning: "tab개수는 최대 %1개까지만 허용됩니다.",
    TabControl_close: "닫기",
    TabControl_close_all: "전체 닫기",
    TabControl_right_corner: "오른쪽 모서리 이미지",
    TabControl_left_corner: "왼쪽 모서리 이미지",
    TabControl_warning1: "[#title]탭이 존재합니다. 기존의 탭을 사용하시려면 '확인'을 새로운 탭을 생성하시려면 '취소'를 선택하세요",
    TabControl_previous_tab: "이전 탭",
    TabControl_next_tab: "다음 탭",
    TabControl_tab_list: "탭 목록",
    TabControl_selected: "%1 선택됨",  
    //autoComplete
    AutoComplete_addItem_invalid: "해당 item의 value값이 %1의 %2번째 위치에 이미 존재합니다. value값은 유일해야 합니다.",
    AutoComplete_all: "-전체-",
    AutoComplete_choose: "-선택-",
    AutoComplete_inputFormat: "입력서식 레이블",
    AutoComplete_label: "자동완성",
    
    // grid
    Grid_sort_none: "정렬 취소",
    Grid_sort_asc: "오름차순 정렬",
    Grid_sort_desc: "내림차순 정렬",
    Grid_filter_title: "사용자 지정 필터",
    Grid_filter_search: "검색",
    Grid_filter_search_label: "찾을 조건",
    Grid_filter_condition1: "시작문자",
    Grid_filter_condition2: "제외할 시작 문자",
    Grid_filter_condition3: "끝 문자",
    Grid_filter_condition4: "제외할 끝 문자",
    Grid_filter_condition5: "포함",
    Grid_filter_condition6: "포함하지 않음",
    Grid_filter_condition7: "= (메타문자 사용)",
    Grid_filter_info_Label1: "? 기호를 사용하여 한문자를 나타낼 수 있습니다.",
    Grid_filter_info_Label2: "* 기호를 사용하여 여러 문자를 나타낼 수 있습니다.",
    Grid_filter_confirm: "확인",
    Grid_filter_cancel: "취소",
    Grid_filter_reset: "초기화",
    Grid_filter_button: "필터 버튼",
    Grid_Customized_Filter: "사용자필터",
    Grid_column_hide: "선택 컬럼 숨기기",
    Grid_column_showAll: "전체 컬럼 숨기기 해제",
    Grid_column_fix: "선택 컬럼 틀고정",
    Grid_column_unfix: "전체 컬럼 틀고정 취소",
    Grid_column_adjustWidth: "선택 컬럼 크기 자동 맞추기",
    Grid_column_adjustAuto: "전체 컬럼 크기 자동 맞추기",
    Grid_column_adjustAuto_none: "전체 컬럼 크기 자동 맞추기 해제",
    Grid_fold_all: "전체 그룹 접기",
    Grid_unfold_all: "전체 그룹 펼치기",
    Grid_ungroup_all: "전체 그룹 해제",
    Grid_ungroup: "선택 컬럼 그룹 해제",
    Grid_group: "선택 컬럼 그룹",
    Grid_noResultMessage: "조회 결과가 없습니다.",
    Grid_scrollMsg: "화면 갱신 중 입니다...",
    Grid_all: "-전체-",
    Grid_checked_all: "전체선택",
    Grid_incorrect_inputType: "cell의 inputType이 올바르지 않습니다.",
    Grid_warning1: "선택하신 컬럼은 checkbox가 아닙니다.",
    Grid_warning2: "입력 데이터의 타입이 잘못되었습니다. true/false boolean 타입으로 입력하세요",
    Grid_warning3: "inputType이 checkbox나 radio가 아닙니다.",
    Grid_warning4: "[%1] [%2] 설정을 변경하는 기능은 아직 지원되지 않습니다",
    Grid_warning5: "%1 adaptive를 지원하지 않는 Grid 입니다.",
    Grid_warning6: "%1 groupby가 활성화되어서 lazyDrawHiddenColumn 속성이 비활성화 되었습니다.",
    Grid_warning7: "%1 : rowSpan이 있기 때문에 lazyDrawHiddenColumn 속성이 비활성화 되었습니다.",
    Grid_warning8: "Cell 개수가 제한 크기를 초과 하였습니다.\n제한 개수 : %1",
    Grid_warning9: "전송 data가 제한 크기를 초과 하였습니다.\n 제한 크기 : %1 byte",
    Grid_warning10: "Row 개수가 제한 크기를 초과 하였습니다.\n제한 개수 : %1",
    Grid_caption: " 을(를) 나타낸 표",
    Grid_caption2: "은(는) ",
    Grid_caption_shortcut: "CTRL 키와 END 키를 동시에 누르면 포커스가 테이블의 마지막 셀로 이동합니다.",
    Grid_footer_caption: "합계를 나타낸 표",
    Grid_title: " 선택",
    Grid_title_not_choose: " 선택 안함",
    Grid_title_partial: " 부분 선택",
    Grid_button: " 버튼",
    Grid_select: " 셀렉트",
    Grid_calendar: " 캘린더",
    Grid_secret: " 시크릿",
    Grid_text: " 텍스트",
    Grid_link: " 링크",
    Grid_autoComplete: " 오토컴플릿",
    Grid_more_Button: "목록 더보기",
    Grid_rowStatus_initialValue: "초기값", // R
    Grid_rowStatus_update: "갱신", // U
    Grid_rowStatus_insert: "삽입", // C
    Grid_rowStatus_delete: "삭제", // D
    Grid_rowStatus_D_After_C: "삽입 후 삭제", // V
    Grid_cases: "건",
    Grid_dom_start: "그리드 시작",
    Grid_dom_end: "그리드 끝",
    Grid_row: "행",
    Grid_column: "열",
    Grid_groupby_count: "건",
    //fwGanttChart
    fwGanttChart_ampm: "오전,오후",
    fwGanttChart_yearSuffix: "년",
    fwGanttChart_monthSuffix: "월",
    fwGanttChart_dateSuffix: "일",
    fwGanttChart_timeGap3Label: "자정,오전 3시,오전 6시,오전 9시,정오,오후 3시,오후 6시,오후 9시",
    fwGanttChart_timeGap6Label: "자정,오전 6시,정오,오후 6시",
    fwGanttChart_quarterNames: "1분기,2분기,3분기,4분기",
    fwGanttChart_monthNames: "1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월",
    //mapchart
    Map_name_39: "제주",
    Map_name_38: "경남",
    Map_name_36: "전남",
    Map_name_35: "전북",
    Map_name_34: "충남",
    Map_name_33: "충북",
    Map_name_32: "강원",
    Map_name_31: "경기",
    Map_name_29: "세종",
    Map_name_26: "울산",
    Map_name_25: "대전",
    Map_name_24: "광주",
    Map_name_22: "대구",
    Map_name_21: "부산",
    Map_name_11: "서울",
    Map_name_37: "경북",
    Map_name_23: "인천",
    // upload
    Upload_ignore_spaces: "공백무시",
    Upload_include_spaces: "공백포함",
    Upload_advanced: "고급설정",
    Upload_hidden_values: "히든값유무",
    Upload_include: "포함",
    Upload_not_include: "미포함",
    Upload_fill_hidden: "히든 채움",
    Upload_sheet_no: "시트 No",
    Upload_starting_row: "시작 row",
    Upload_starting_col: "시작 col",
    Upload_header: "헤더 유무",
    Upload_footer: "푸터 유무",
    Upload_file: "파일 업로드",
    Upload_file_title: "파일 업로드",
    Upload_file_header: "파일 업로드",
    Upload_file_choose: "파일 선택",
    Upload_file_span: "선택된 파일 없음",
    Upload_fill: "채움",
    Upload_ignore: "무시",
    Upload_pwd: "비밀번호",
    Upload_msg1: "파일 업로드를 위한 임시 프레임",
    Upload_msg2: "파일 사이즈가 제한 용량을 초과 하였습니다.",
    Upload_msg3: "정상적으로 처리 되지 않았습니다.",
    Upload_msg4: "FileType에 맞지 않는 File의 확장자입니다.",
    Upload_msg5: "그리드 반영에 실패하였습니다",
    Upload_msg6: "데이터 수집 중..",
    Upload_msg7: "데이터 변환 완료",
    Upload_msg8: "비밀번호가 일치하지 않습니다.",
    Upload_msg9: "허용하지 않는 확장자 입니다.",
    Upload_msg10: "DRM 연계시 오류가 발생하였습니다.",
    Upload_msg11: "업로드 제한 건수를 초과하였습니다.",
    Upload_msg12: "유효하지 않은 엑셀 형식입니다.",
    Upload_msg13: "유효하지 않은 셀 서식입니다.",
    Upload_msg14: "업로드 셀건수제한을 초과하였습니다.",
    Upload_msg15: "파일이 암호화되어 있습니다.",
    Upload_msg16: "Excel 5.0/7.0은 지원하지 않습니다.",
    Upload_msg17: "지정 sheet가 존재하지 않습니다.",
    Upload_msg18: "쓰기 전용 파일이거나 읽을수 없는 파입니다.",
    Upload_warning1: "보안상의 문제로 사용할 수 없는 기능입니다.",
    //itemTable
    itemTable_confirm: "선택적용",
    itemTable_cancel: "선택해제",
    //pivot
    Pivot_canNotMoveToHiddenList: "숨김 영역으로 이동할 수 없습니다.",
    Pivot_sum: "합계",
    Pivot_average: "평균",
    Pivot_count: "갯수",
    Pivot_min: "최소값",
    Pivot_max: "최대값",
    Pivot_renderError: "PivotTable을 랜더링하던 중에 에러가 발생했습니다.",
    Pivot_computeError: "PivotTable 데이타를 계산하던 중에 에러가 발생했습니다.",
    Pivot_uiRenderError: "PivotTable UI를 랜더링하던 중에 에러가 발생했습니다.",
    Pivot_dragError: "총합계는 Value 영역으로 드래그할 수 없습니다.",
    Pivot_selectAll: "전체 선택",
    Pivot_selectNone: "전체 해제",
    Pivot_tooMany: "(목록으로 보여 줄 값이 너무 많습니다.)",
    Pivot_filterResults: "필터링할 항목을 입력하세요.",
    Pivot_totals: "총합계",
    Pivot_vs: "vs",
    Pivot_by: "by",
    Pivot_apply: "적용",
    Pivot_cancel: "닫기",
    //slideHide
    SlideHide_btnHide: "접기",
    SlideHide_btnShow: "펼치기",
    SlideHide_btnToggle: "확장 축소 버튼",
    //switch
    Switch_btnPrev: "이전",
    Switch_btnNext: "다음",
    Switch_pagination_ariaLabel: "%1개중에 %2번째 슬라이드로 이동",
    Switch_case_ariaRoledesc: "슬라이드",
    Switch_case_ariaLabel: "%1개중 %2번째",
    Switch_selected_pagination: "선택됨",
    //searchbox
    Searchbox_ariaLabel: "검색서식",
    Searchbox_resetButton_ariaLabel: "입력내용 삭제",
    //treeview
    Treeview_iconNaviAriaLabel: "확장 축소 버튼",
    Treeview_warning1: "treeview를 동적으로 처리하는 경우에는  dynamicAppend='true'로 설정하는 것을 권장합니다.",
    Treeview_warning2: "treeview의 accordion 모드에서는 %1 API를 지원하지 않습니다.",
    //multiselect
    multiselect_ariaLabel: "다중선택 영역",
    //editor
    Editor_currentChar: "글자",
    Editor_maxChar_warning: "%1자를 초과할 수 없습니다.",
    Editor_warning_load_default_version: "기본 버전인 %1로 로딩됩니다",
    Editor_warning_incorrect_editor_version: "에디터 버전이 올바르지 않습니다",
    Editor_warning_no_resource: "에디터 버전에 해당하는 리소스가 없습니다",
    //scheduleCalendar
    scheduleCalendar_schedule: "일정",
    //performance
    Performance_step1 : "브라우저 URL 호출을 시작하는 순간부터 BootLoader 로딩이 완료될 때까지 걸리는 시간입니다. BootLoader는 웹스퀘어 엔진 초기 시작에 필수적인 요소입니다",
    Performance_step2 : "BootLoader 실행 완료부터 웹스퀘어 엔진 전체 로딩이 완료될 때까지 걸리는 시간입니다.",
    Performance_step3 : "웹스퀘어 엔진 로딩 완료부터 웹스퀘어 페이지 파일, 공통 JS 및 CSS 파일 로딩이 완료될 때까지 걸리는 시간입니다.",
    Performance_step4 : "리소스(웹스퀘어 페이지 파일, 공통 JS 및 CSS 파일) 로딩 완료부터 웹스퀘어 컴포넌트 객체가 생성될 때까지 걸리는 시간입니다.",
    Performance_step5 : "컴포넌트 객체 생성 완료부터 컴포넌트의 렌더링이 완료될 때까지 걸리는 시간입니다.",
    Performance_step6 : "컴포넌트 렌더링 완료부터 컴포넌트 전처리 작업이 완료될 때까지 걸리는 시간입니다.",
    Performance_step7 : "컴포넌트 전처리 작업 완료부터 컴포넌트 초기화 작업이 완료될 때까지 걸리는 시간입니다.",
    Performance_step8 : "컴포넌트 초기화 작업 완료부터 initScript 실행이 완료될 떄까지 걸리는 시간입니다. 단, initScript 내의 비동기 처리 시간은 제외됩니다.",
    Performance_step9 : "initScript 실행 완료부터 onpageload 이벤트 실행이 완료될 때까지 걸리는 시간입니다. 단, onpageload내의 비동기 처리 시간은 제외됩니다.",
    Performance_step10 : "onpageload 실행 완료부터 postScript 실행이 완료될 때까지 걸리는 시간입니다. 단, postScript 내의 비동기 처리 시간은 제외됩니다. 이 단계에서 웹스퀘어 초기화가 완료되지만 비동기 처리 시간은 제외됩니다.",
    Performance_event : "이 측정 지표는 이벤트 핸들러가 이벤트 시작부터 완료될 때까지 실행하는 데 걸리는 시간을 측정합니다. 핸들러 내의 비동기 부분은 제외됩니다. 특정 이벤트 유형에 대한 자세한 내용은 type 속성 값을 참조하십시오.",
    Performance_submission_start : "submission 시작 시점부터 customHandler 함수 호출이 완료될 때까지 걸리는 시간입니다. 단, customHandler가 비동기인 경우엔 비동기 처리에 걸리는 시간은 제외됩니다.",
    Performance_submission_end_replaceAll : "replace='all' 모드일 때, submission 시작 시점부터 submission 처리가 완료될 때까지 걸리는 시간입니다. 여기에는 <form> 태그 생성 및 form.submit을 통해 submissiono을 처리하는 시간을 포함합니다.",
    Performance_submission_step1 : "submission 실행부터 네트워크에 url 요청을 보내기 직전까지 걸리는 시간입니다.",
    Performance_submission_end_error_script : "submission 실행부터 submission 처리 중 오류가 발생하여 중단될 때까지 걸리는 시간입니다.",
    Performance_submission_step2 : "submission url에 대한 네트워크 요청을 보낸 시점부터 네트워크 응답이 도착하여 commonResponseHandler 콜백 함수가 시작될 때까지 걸리는 시간입니다.",
    Performance_submission_end_error_network : "submission url에 대한 네트워크 요청을 보낸 시점부터 네트워크 응답 실패로 인해 submission이 강제 종료될 때까지 걸리는 시간입니다. 이 측정 지표에는 네트워크 상태 코드(%1)가 포함됩니다.",
    Performance_submission_step3 : "submission의 callback 함수 commonResponseHandler를 시작하는 순간부터 submssion의 ref 속성과 target 속성 처리 완료까지 걸리는 시간입니다.",
    Performance_submission_end_ok : "submssion의 ref 속성과 target 속성 처리 완료부터 사용자 이벤트 onsubmitdone이 실행 완료될 때까지 걸리는 시간입니다. 이는 submission 처리가 완료되었음을 의미합니다.",
    Performance_wframe_step1: "wframe 생성부터 웹스퀘어 페이지 파일 로딩과 DOM 렌더링(toHTML) 완료까지 걸리는 시간입니다.",
    Performance_wframe_step2: "wframe의 initScript, onpageload, postScript 이벤트 실행 시간입니다. 이는 wframe 처리가 완료되었음을 나타냅니다. 총 경과 시간은 step1과 step2의 합입니다.",
    //accessibility
    Accssibility_btn_aria_label_windowContainer: "창 닫기"
};